"""HOSE-style codes: a canonical string for an atom's surroundings.

The idea is Bremser's (1978): describe an atom by walking outward in
concentric spheres and writing what you find, so that two atoms in the
same environment produce the same string no matter which molecules they
came from or how those molecules were numbered. Shift prediction then
becomes a lookup -- find database atoms whose code matches, average their
measured shifts -- and the SPREAD of those matches is a real, earned
measure of confidence rather than an invented one.

NAMED "HOSE-STYLE", NOT "HOSE", AND THE DISTINCTION IS DELIBERATE. The
canonical reference implementation is CDK's `HOSECodeGenerator`, which is
Java, and there is no JVM on this machine to check against -- the same
gap that blocks STOUT. Rather than claim byte-compatibility with a
published format nobody here can verify, this generates its own
well-defined code and states so. Nothing is lost for prediction: both
sides of the lookup, the database and the query, are generated by THIS
function, so they only have to agree with each other. Byte-compatibility
would only matter for exchanging codes with other software.

WHAT MAKES IT WORK, and what the tests pin:

  * Deterministic -- the same environment always gives the same string.
  * Input-order independent -- renumbering a molecule cannot change it.
    This is the one that is easy to get wrong: RDKit's canonical ranks
    are a property of the WHOLE molecule, so using them to order branches
    would make identical local environments in different molecules
    produce different codes, and silently break every lookup. Branches
    are therefore ordered by their OWN recursively-built strings, which
    depend only on what is inside them.
  * Symmetry-respecting -- benzene's six carbons share one code.
  * Discriminating -- toluene's ortho, meta and para carbons do not.

Codes are generated at every sphere depth, largest first, so a lookup can
fall back: an exact four-sphere match is a near-identical environment,
while a two-sphere match is a looser one covering more of the database.

CALL THESE ON A HEAVY-ATOM MOLECULE. The walk follows every bond, so an
EXPLICIT hydrogen is written into the code and an implicit one is not --
which means the same molecule drawn two ways produces two different
codes, and neither matches the other. That is not hypothetical: 34.3% of
nmrshiftdb2's records carry explicit hydrogens, so the shift index was
really two indexes, and toluene's methyl looked up from `Chem.AddHs(...)`
returned 8.89 ppm against a literature 21.4. `nmr_database.heavy_atom_view`
is what both sides now normalise through; there is no reason to code from
anything else.
"""

from __future__ import annotations

from rdkit import Chem

# Bond symbols, following the convention HOSE codes use.
_BOND_SYMBOL = {
    Chem.BondType.SINGLE: "",
    Chem.BondType.DOUBLE: "=",
    Chem.BondType.TRIPLE: "%",
    Chem.BondType.AROMATIC: "*",
}

# Marks a bond back to an atom already seen on this walk. Without it a
# ring and a chain of the same length would look identical.
_RING_CLOSURE = "&"

DEFAULT_MAX_SPHERES = 4


def _bond_symbol(bond: Chem.Bond) -> str:
    if bond.GetIsAromatic():
        return "*"
    return _BOND_SYMBOL.get(bond.GetBondType(), "?")


def _atom_symbol(atom: Chem.Atom) -> str:
    """Element, plus charge when there is one.

    Hydrogens are not written as atoms: they are implied by the heavy-atom
    skeleton and writing them would make every code longer without
    distinguishing anything a database lookup cares about. A proton's own
    environment is described by walking out from the carbon it sits on.
    """
    symbol = atom.GetSymbol()
    charge = atom.GetFormalCharge()
    if charge > 0:
        return f"{symbol}+" if charge == 1 else f"{symbol}+{charge}"
    if charge < 0:
        return f"{symbol}-" if charge == -1 else f"{symbol}-{abs(charge)}"
    return symbol


def _ordering_key(
    mol: Chem.Mol, atom_index: int, came_from: int, seen: frozenset[int], depth: int
) -> str:
    """A canonical signature for a branch, used only to ORDER siblings.

    A local depth-first walk, which is enough to sort by and -- crucially
    -- depends only on what is inside the branch. A whole-molecule
    canonical rank would sort correctly too and would silently give the
    same environment different codes in different molecules, breaking
    every lookup.
    """
    atom = mol.GetAtomWithIdx(atom_index)
    if depth <= 0:
        return _atom_symbol(atom)
    seen = seen | {atom_index}
    children = sorted(
        f"{_bond_symbol(bond)}"
        f"{_ordering_key(mol, bond.GetOtherAtomIdx(atom_index), atom_index, seen, depth - 1)}"
        for bond in atom.GetBonds()
        if bond.GetOtherAtomIdx(atom_index) != came_from
        and bond.GetOtherAtomIdx(atom_index) not in seen
    )
    return f"{_atom_symbol(atom)}({','.join(children)})" if children else _atom_symbol(atom)


def hose_code(mol: Chem.Mol, atom_index: int, spheres: int = DEFAULT_MAX_SPHERES) -> str:
    """The code for one atom at one sphere depth.

    Sphere-by-sphere (breadth-first) with a GLOBAL record of which atoms
    have been reached, which is the part that makes rings work. A
    depth-first walk carrying a per-path visited set cannot see a ring
    that closes between two SIBLING branches: walking out from a benzene
    carbon, the two directions round the ring meet at the para carbon,
    and neither branch knows the other was there. The ring is then never
    marked closed and the shared atom is counted twice, so a ring reads
    exactly like a branched chain -- confirmed live, benzene's four-sphere
    code contained no closure marker at all, and the resulting
    over-pooling put ~4000 unrelated measurements behind a single toluene
    carbon and pulled its prediction 3.7 ppm off.

    Within one sphere, an atom reached from two parents at once is the
    atom on its first (sorted) appearance and a closure marker on the
    rest, so the same ring always closes the same way.

    `spheres` is how far out to look. Deeper means a more specific
    environment and fewer matches; shallower means more matches with more
    scatter among them.
    """
    root = mol.GetAtomWithIdx(atom_index)
    visited = {atom_index}
    # (atom, the atom it was reached from) -- the parent is needed so the
    # next sphere does not report the edge it just came along as a ring
    # closure, which every atom would otherwise do once `visited` is
    # global.
    layer: list[tuple[int, int | None]] = [(atom_index, None)]
    sphere_parts: list[str] = []

    for remaining in range(spheres, 0, -1):
        # (sort key, display token, neighbour, parent, is_closure)
        candidates: list[tuple[str, str, int, int, bool]] = []
        for parent, grandparent in layer:
            for bond in mol.GetAtomWithIdx(parent).GetBonds():
                neighbour = bond.GetOtherAtomIdx(parent)
                if neighbour == grandparent:
                    continue
                symbol = _bond_symbol(bond)
                if neighbour in visited:
                    closure = f"{symbol}{_RING_CLOSURE}"
                    candidates.append((closure, closure, neighbour, parent, True))
                    continue
                display = f"{symbol}{_atom_symbol(mol.GetAtomWithIdx(neighbour))}"
                key = _ordering_key(mol, neighbour, parent, frozenset(visited), remaining - 1)
                candidates.append((f"{display}|{key}", display, neighbour, parent, False))

        if not candidates:
            break
        candidates.sort(key=lambda entry: entry[0])

        tokens: list[str] = []
        next_layer: list[tuple[int, int | None]] = []
        claimed: dict[int, int] = {}
        for _key, display, neighbour, parent, is_closure in candidates:
            if is_closure:
                tokens.append(display)
                continue
            if neighbour in claimed:
                # Reached twice within this same sphere, from two
                # different parents -- that is a ring closing across
                # branches, which is exactly what the old depth-first walk
                # could not see.
                tokens.append(f"{display[: -len(_atom_symbol(mol.GetAtomWithIdx(neighbour)))]}{_RING_CLOSURE}")
                continue
            claimed[neighbour] = parent
            tokens.append(display)
            next_layer.append((neighbour, parent))

        visited |= set(claimed)
        sphere_parts.append(",".join(tokens))
        layer = next_layer
        if not layer:
            break

    return f"{_atom_symbol(root)};" + "/".join(sphere_parts)


def hose_codes(
    mol: Chem.Mol, atom_index: int, max_spheres: int = DEFAULT_MAX_SPHERES
) -> list[str]:
    """Codes for one atom at every depth, LARGEST FIRST.

    Largest first because that is the order a lookup wants to try them:
    take the most specific environment that has enough matches to average,
    and only widen when it does not.
    """
    return [hose_code(mol, atom_index, sphere) for sphere in range(max_spheres, 0, -1)]


def hose_codes_for_element(
    mol: Chem.Mol, element: str, max_spheres: int = DEFAULT_MAX_SPHERES
) -> dict[int, list[str]]:
    """Every atom of `element`, mapped to its codes.

    A proton is described by the environment of the heavy atom it is
    attached to, because that is what determines its shift -- and because
    a hydrogen has no surroundings of its own beyond that one bond. Two
    protons on the same carbon therefore share a code, which is correct:
    they are equivalent unless something further out distinguishes them.
    """
    codes: dict[int, list[str]] = {}
    for atom in mol.GetAtoms():
        if atom.GetSymbol() != element:
            continue
        if element == "H":
            neighbours = atom.GetNeighbors()
            if not neighbours:
                continue
            codes[atom.GetIdx()] = hose_codes(mol, neighbours[0].GetIdx(), max_spheres)
        else:
            codes[atom.GetIdx()] = hose_codes(mol, atom.GetIdx(), max_spheres)
    return codes
