"""HOSE-style codes: a canonical string for an atom's surroundings.

The idea is Bremser's (1978): describe an atom by walking outward in
concentric spheres and writing what you find, so that two atoms in the
same environment produce the same string no matter which molecules they
came from or how those molecules were numbered. Shift prediction then
becomes a lookup -- find database atoms whose code matches, average their
measured shifts -- and the SPREAD of those matches is a real, earned
measure of confidence rather than an invented one.

NAMED "HOSE-STYLE", NOT "HOSE", AND THE DISTINCTION IS DELIBERATE. The
canonical reference implementation is CDK's `HOSECodeGenerator`, which is
Java, and there is no JVM on this machine to check against -- the same
gap that blocks STOUT. Rather than claim byte-compatibility with a
published format nobody here can verify, this generates its own
well-defined code and states so. Nothing is lost for prediction: both
sides of the lookup, the database and the query, are generated by THIS
function, so they only have to agree with each other. Byte-compatibility
would only matter for exchanging codes with other software.

WHAT MAKES IT WORK, and what the tests pin:

  * Deterministic -- the same environment always gives the same string.
  * Input-order independent -- renumbering a molecule cannot change it.
    This is the one that is easy to get wrong: RDKit's canonical ranks
    are a property of the WHOLE molecule, so using them to order branches
    would make identical local environments in different molecules
    produce different codes, and silently break every lookup. Branches
    are therefore ordered by their OWN recursively-built strings, which
    depend only on what is inside them.
  * Symmetry-respecting -- benzene's six carbons share one code.
  * Discriminating -- toluene's ortho, meta and para carbons do not.

Codes are generated at every sphere depth, largest first, so a lookup can
fall back: an exact four-sphere match is a near-identical environment,
while a two-sphere match is a looser one covering more of the database.
"""

from __future__ import annotations

from rdkit import Chem

# Bond symbols, following the convention HOSE codes use.
_BOND_SYMBOL = {
    Chem.BondType.SINGLE: "",
    Chem.BondType.DOUBLE: "=",
    Chem.BondType.TRIPLE: "%",
    Chem.BondType.AROMATIC: "*",
}

# Marks a bond back to an atom already seen on this walk. Without it a
# ring and a chain of the same length would look identical.
_RING_CLOSURE = "&"

DEFAULT_MAX_SPHERES = 4


def _bond_symbol(bond: Chem.Bond) -> str:
    if bond.GetIsAromatic():
        return "*"
    return _BOND_SYMBOL.get(bond.GetBondType(), "?")


def _atom_symbol(atom: Chem.Atom) -> str:
    """Element, plus charge when there is one.

    Hydrogens are not written as atoms: they are implied by the heavy-atom
    skeleton and writing them would make every code longer without
    distinguishing anything a database lookup cares about. A proton's own
    environment is described by walking out from the carbon it sits on.
    """
    symbol = atom.GetSymbol()
    charge = atom.GetFormalCharge()
    if charge > 0:
        return f"{symbol}+" if charge == 1 else f"{symbol}+{charge}"
    if charge < 0:
        return f"{symbol}-" if charge == -1 else f"{symbol}-{abs(charge)}"
    return symbol


def _branch(
    mol: Chem.Mol, atom_index: int, came_from: int | None, seen: frozenset[int], depth: int
) -> str:
    """The code for everything reachable from `atom_index` within `depth`.

    Recursive by construction: a branch's string is built from its
    children's strings, which is also what orders them. That ordering has
    to depend only on the branch's own contents -- see the module note on
    why a whole-molecule canonical rank cannot be used here.
    """
    atom = mol.GetAtomWithIdx(atom_index)
    if depth <= 0:
        return _atom_symbol(atom)

    seen = seen | {atom_index}
    children = []
    for bond in atom.GetBonds():
        neighbour = bond.GetOtherAtomIdx(atom_index)
        if neighbour == came_from:
            continue
        if neighbour in seen:
            # A ring closing back on the walk. Recorded as a marker rather
            # than followed, or the recursion would loop.
            children.append(f"{_bond_symbol(bond)}{_RING_CLOSURE}")
            continue
        children.append(
            f"{_bond_symbol(bond)}{_branch(mol, neighbour, atom_index, seen, depth - 1)}"
        )

    if not children:
        return _atom_symbol(atom)
    return f"{_atom_symbol(atom)}({','.join(sorted(children))})"


def hose_code(mol: Chem.Mol, atom_index: int, spheres: int = DEFAULT_MAX_SPHERES) -> str:
    """The code for one atom at one sphere depth.

    `spheres` is how far out to look. Deeper means a more specific
    environment and fewer database matches; shallower means more matches
    with more scatter among them.
    """
    return _branch(mol, atom_index, None, frozenset(), spheres)


def hose_codes(
    mol: Chem.Mol, atom_index: int, max_spheres: int = DEFAULT_MAX_SPHERES
) -> list[str]:
    """Codes for one atom at every depth, LARGEST FIRST.

    Largest first because that is the order a lookup wants to try them:
    take the most specific environment that has enough matches to average,
    and only widen when it does not.
    """
    return [hose_code(mol, atom_index, sphere) for sphere in range(max_spheres, 0, -1)]


def hose_codes_for_element(
    mol: Chem.Mol, element: str, max_spheres: int = DEFAULT_MAX_SPHERES
) -> dict[int, list[str]]:
    """Every atom of `element`, mapped to its codes.

    A proton is described by the environment of the heavy atom it is
    attached to, because that is what determines its shift -- and because
    a hydrogen has no surroundings of its own beyond that one bond. Two
    protons on the same carbon therefore share a code, which is correct:
    they are equivalent unless something further out distinguishes them.
    """
    codes: dict[int, list[str]] = {}
    for atom in mol.GetAtoms():
        if atom.GetSymbol() != element:
            continue
        if element == "H":
            neighbours = atom.GetNeighbors()
            if not neighbours:
                continue
            codes[atom.GetIdx()] = hose_codes(mol, neighbours[0].GetIdx(), max_spheres)
        else:
            codes[atom.GetIdx()] = hose_codes(mol, atom.GetIdx(), max_spheres)
    return codes
