"""The periodic-table reference: the data, and what the dialog says about it.

`elements.json` is generated by `tools/build_element_reference.py`, which
asserts its own invariants at build time. Those same invariants are
re-checked here against the COMMITTED file, so a hand edit is caught even
though the generator was not re-run.

Everything else RDKit already knows and is not duplicated -- so the tests
that matter most are the ones checking the two sources agree, and the ones
checking that an unknown fact is reported as unknown rather than blank.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from rdkit import Chem

from openchem.chem.element_reference import (
    all_symbols,
    f_block_series,
    facts_for,
    grid_position,
)
from openchem.ui.dialogs.periodic_table_dialog import describe

_DATA = Path("src/openchem/chem/data/elements.json")


@pytest.fixture(scope="module")
def raw() -> dict:
    root = Path(__file__).resolve().parent.parent
    return json.loads((root / _DATA).read_text(encoding="utf-8"))["elements"]


# --- the generator's invariants, re-checked on the committed file -----------


def test_every_element_is_present(raw):
    assert len(raw) == 118
    assert {entry["atomic_number"] for entry in raw.values()} == set(range(1, 119))


def test_every_electron_configuration_accounts_for_exactly_z(raw):
    """The check that makes a generated table better than a typed one.

    An electron configuration is a claim with an arithmetic consequence:
    the occupancies must sum to the atomic number. A typo anywhere in 118
    of them fails here.
    """
    subshells = {"s": 2, "p": 6, "d": 10, "f": 14}
    cores = {"[He]": 2, "[Ne]": 10, "[Ar]": 18, "[Kr]": 36, "[Xe]": 54, "[Rn]": 86}

    for symbol, entry in raw.items():
        total = 0
        for token in entry["electron_configuration"].split():
            if token in cores:
                total += cores[token]
                continue
            assert token[1] in subshells, f"{symbol}: {token}"
            count = int(token[2:])
            assert count <= subshells[token[1]], f"{symbol}: {token} overfills its subshell"
            total += count
        assert total == entry["atomic_number"], f"{symbol}: configuration holds {total} electrons"


def test_no_two_elements_claim_the_same_grid_cell(raw):
    seen: dict[tuple[int, int], str] = {}
    for symbol, entry in raw.items():
        if entry["group"] is None:
            continue
        cell = (entry["period"], entry["group"])
        assert cell not in seen, f"{symbol} collides with {seen[cell]} at {cell}"
        seen[cell] = symbol


def test_the_block_agrees_with_the_group_it_was_placed_in(raw):
    for symbol, entry in raw.items():
        group, block = entry["group"], entry["block"]
        if group is None:
            assert block == "f", symbol
        elif symbol == "He":
            assert block == "s"  # group 18 by position, s-block by configuration
        elif group in (1, 2):
            assert block == "s", symbol
        elif 3 <= group <= 12:
            assert block == "d", symbol
        else:
            assert block == "p", symbol


@pytest.mark.parametrize(
    "symbol, period, group, block",
    [
        ("H", 1, 1, "s"),
        ("He", 1, 18, "s"),
        ("C", 2, 14, "p"),
        ("Ne", 2, 18, "p"),
        ("Cl", 3, 17, "p"),
        ("Sc", 4, 3, "d"),
        ("Fe", 4, 8, "d"),
        ("Zn", 4, 12, "d"),
        ("Ga", 4, 13, "p"),
        ("Ag", 5, 11, "d"),
        ("Hf", 6, 4, "d"),
        ("Au", 6, 11, "d"),
        ("Pb", 6, 14, "p"),
        ("Rn", 6, 18, "p"),
        ("Rf", 7, 4, "d"),
        ("Og", 7, 18, "p"),
    ],
)
def test_landmark_positions(symbol, period, group, block):
    """Sixteen places a chemist would notice instantly if the layout were
    wrong -- the ends of every period, both sides of the d-block, and the
    two rows that have to skip the f-block series."""
    facts = facts_for(symbol)

    assert (facts.period, facts.group, facts.block) == (period, group, block)


def test_the_f_block_has_fifteen_of_each_and_no_grid_column():
    lanthanides, actinides = f_block_series()

    assert (lanthanides[0], lanthanides[-1], len(lanthanides)) == ("La", "Lu", 15)
    assert (actinides[0], actinides[-1], len(actinides)) == ("Ac", "Lr", 15)
    assert grid_position("Gd") is None
    assert grid_position("U") is None


@pytest.mark.parametrize(
    "symbol, configuration",
    [
        ("Fe", "[Ar] 3d6 4s2"),
        ("Cr", "[Ar] 3d5 4s1"),  # anomaly
        ("Cu", "[Ar] 3d10 4s1"),  # anomaly
        ("Pd", "[Kr] 4d10"),  # anomaly: no 5s at all
        ("Ag", "[Kr] 4d10 5s1"),  # anomaly
        ("La", "[Xe] 5d1 6s2"),  # anomaly: no 4f
        ("Gd", "[Xe] 4f7 5d1 6s2"),  # anomaly
        ("Au", "[Xe] 4f14 5d10 6s1"),  # anomaly
        ("U", "[Rn] 5f3 6d1 7s2"),  # anomaly
    ],
)
def test_the_known_aufbau_anomalies_are_right(symbol, configuration):
    """Eight of the twenty exceptions, spot-checked against their measured
    ground states. Palladium is the strictest: it has no outer s electrons
    at all, which a naive filling never produces."""
    assert facts_for(symbol).electron_configuration == configuration


def test_configurations_read_in_shell_order_not_filling_order():
    """Aufbau fills 4s before 3d, but iron is universally written
    [Ar] 3d6 4s2. A table that printed the loop's order would be correct
    and unreadable."""
    assert facts_for("Fe").electron_configuration == "[Ar] 3d6 4s2"


# --- the merge with RDKit ---------------------------------------------------


def test_nothing_rdkit_already_knows_is_duplicated_in_the_file(raw):
    """The file exists for what RDKit lacks. A weight or a radius copied
    into it is a second source of truth that will drift."""
    forbidden = {"name", "atomic_weight", "van_der_waals_radius", "covalent_radius", "isotopes"}

    for symbol, entry in raw.items():
        assert not (forbidden & set(entry)), f"{symbol} duplicates RDKit data"


def test_names_and_weights_come_from_rdkit():
    table = Chem.GetPeriodicTable()
    facts = facts_for("Fe")

    assert facts.name == table.GetElementName(26)
    assert facts.atomic_weight == table.GetAtomicWeight(26)


def test_isotopes_come_with_abundances():
    """RDKit carries the full natural-abundance table, which is why none of
    this is hand-entered."""
    iron = {isotope.mass_number: isotope.abundance for isotope in facts_for("Fe").isotopes}

    assert set(iron) == {54, 56, 57, 58}
    assert iron[56] == pytest.approx(91.754, abs=0.01)
    assert sum(iron.values()) == pytest.approx(100.0, abs=0.05)


@pytest.mark.parametrize("symbol", ["Tc", "Pm", "Og", "Rf"])
def test_elements_with_no_natural_isotopes_report_none(symbol):
    """Technetium is the famous gap in the table, and everything past
    bismuth is the same story. Zero isotopes is the fact, not missing
    data."""
    assert facts_for(symbol).isotopes == ()


def test_a_transition_metal_reports_no_defined_valence():
    """RDKit's valence list for iron is `[-1]`, meaning undefined. Shown as
    a sentence rather than as the literal -1, which would read as a
    valence of minus one."""
    assert facts_for("Fe").valences is None
    assert facts_for("C").valences == (4,)


def test_electronegativity_comes_from_the_existing_sourced_table():
    assert facts_for("Fe").electronegativity == 1.83
    assert facts_for("F").electronegativity == 3.98


def test_an_element_with_no_accepted_electronegativity_reports_none():
    assert facts_for("He").electronegativity is None


def test_an_unknown_symbol_is_none_rather_than_an_exception():
    assert facts_for("Xx") is None


# --- what the dialog says ---------------------------------------------------


def test_the_detail_pane_names_the_category_in_words():
    """Colour marks category in the grid, but never alone. Ten categories
    separated by hue is unreadable to a fair number of people."""
    text = describe(facts_for("Fe"))

    assert "Transition metal" in text


def test_an_undefined_valence_is_explained_rather_than_left_blank():
    """Added after mutation testing: blanking this line failed nothing.

    "No defined valence" is the correct fact about every transition metal
    and is the same one the valence checker acts on -- but a blank cell
    beside "Typical valences" reads as missing data, which is the opposite
    of what it means.
    """
    text = describe(facts_for("Fe"))

    assert "no defined valence (normal for a metal)" in text


def test_a_superheavy_nonmetal_does_not_claim_to_be_a_metal():
    """75 elements report no valence list. For 73 that is real chemistry
    about metals; tennessine and oganesson are the other two, where almost
    nothing is known -- and calling those "normal for a metal" is wrong
    twice over. Caught by looking at the real dialog, not by a test."""
    for symbol in ("Og", "Ts"):
        text = describe(facts_for(symbol))
        assert "no defined valence is tabulated" in text, symbol
        assert "normal for a metal" not in text, symbol


def test_the_detail_pane_reports_what_is_not_established():
    """Oganesson has been made a handful of atoms at a time. A blank row
    would read as a bug; "not established" is the true answer."""
    text = describe(facts_for("Og"))

    assert "not established" in text
    assert "no naturally occurring isotopes" in text
    assert "no accepted value" in text  # electronegativity


def test_the_detail_pane_carries_the_facts_it_promises():
    text = describe(facts_for("Fe"))

    for expected in ("Iron", "[Ar] 3d6 4s2", "1.83", "55.845", "haemoglobin"):
        assert expected in text, expected
    assert "<sup>56</sup>Fe" in text


def test_the_atomic_mass_keeps_enough_digits_to_be_useful():
    """Four significant figures renders uranium as "238" and iron as
    "55.84". A reference table that drops the digits somebody opened it
    for is not much of a reference."""
    assert "238.029" in describe(facts_for("U"))
    assert "55.845" in describe(facts_for("Fe"))


def test_oxidation_states_are_written_with_a_sign():
    text = describe(facts_for("Fe"))

    assert "+3" in text and "+2" in text


def test_every_element_can_be_described_without_raising():
    """118 of them, including the ones with almost nothing known. The
    detail pane must degrade to sentences, never to a traceback."""
    for symbol in all_symbols():
        assert describe(facts_for(symbol))


# --- packaging --------------------------------------------------------------


def test_the_elements_file_is_in_the_packaging_spec():
    spec = Path(__file__).resolve().parent.parent / "packaging" / "openchem.spec"

    assert "elements.json" in spec.read_text(encoding="utf-8")


# --- A3: the valence row is RDKit's model, and says so ----------------------


def test_the_valence_row_does_not_present_itself_as_curated_chemistry():
    """It used to be captioned "Typical valences".

    `GetValenceList` is RDKit's DEFAULT-VALENCE model, for deciding how
    many hydrogens an atom implies. Measured, it gives Cl [1] and Br [1]
    while I is [1, 3, 5] -- so the old caption told a reader that bromine
    has one typical valence and iodine three, when both do 1/3/5/7. The
    number is worth keeping, because this application's own valence
    checker acts on the same list; the claim was not.
    """
    text = describe(facts_for("Br"))

    assert "Typical valences" not in text
    assert "RDKit" in text
    assert "not a curated chemistry reference" in text


def test_the_valence_caveat_is_on_every_element_not_just_the_awkward_ones():
    """A caveat shown only where the value looks wrong is a caveat that
    teaches the reader to trust the rest."""
    for symbol in ("H", "C", "Fe", "Br", "I", "Og"):
        assert "not a curated chemistry reference" in describe(facts_for(symbol))


# --- A4: a typo detector, and NOT a completeness check ----------------------


#: The categories where an octet-style bound is a meaningful statement.
#: Transition metals and the f-block are deliberately excluded: neither
#: half of the rule below holds for them, and a guard that judged iron
#: would be inventing chemistry rather than catching a typo.
_MAIN_GROUP = frozenset(
    {"nonmetal", "noble_gas", "halogen", "alkali", "alkaline_earth",
     "metalloid", "post_transition"}
)


def test_no_oxidation_state_is_mechanically_impossible():
    """**A TYPO DETECTOR. IT CANNOT CHECK COMPLETENESS, AND MUST NOT BE
    READ AS DOING SO.**

    "No listed state is impossible" is mechanically testable. "Every state
    that should be listed is present" is not, by anything -- that remains
    a source review by a person, and a green tick here is not evidence it
    happened. `_OXIDATION_STATES` in the generator is hand-entered and the
    generated file says so in its own `_about` block.

    ONE RULE, not two. An earlier draft also asserted that the maximum
    positive state does not exceed the group number, which is useless
    where it holds trivially (chlorine's +7 against group 17) and wrong
    as soon as older group numbering is meant.
    """
    for symbol in all_symbols():
        facts = facts_for(symbol)
        if facts.category not in _MAIN_GROUP:
            continue
        for state in facts.common_oxidation_states:
            assert abs(state) <= facts.outer_electrons, (
                f"{symbol} claims {state:+d} with {facts.outer_electrons} outer electrons"
            )


@pytest.mark.parametrize(
    "symbol, states",
    [
        ("H", (1, -1)),      # one outer electron, and it goes both ways
        ("He", ()),          # no states listed at all is a valid answer
        ("F", (-1,)),        # the one element with no positive state
        ("O", (-2,)),
        ("Xe", (2, 4, 6)),   # a noble gas that really does have compounds
        ("Cl", (-1, 1, 3, 5, 7)),  # the widest main-group set shipped
    ],
)
def test_the_awkward_cases_the_rule_has_to_survive(symbol, states):
    """Named fixtures rather than trust in the formula.

    A rule left to speak for itself becomes the authority it was written
    not to be. These are the elements where an octet bound is least
    obviously right, checked one by one -- so a future tightening that
    breaks any of them fails HERE, naming the element, rather than
    somewhere downstream.
    """
    facts = facts_for(symbol)

    assert facts.common_oxidation_states == states
    for state in states:
        assert abs(state) <= facts.outer_electrons
