"""`benchmarks/naming/adjudication.toml` is the target set, so it needs a guard.

**A FIX WITHOUT AN ADJUDICATED TARGET IS AIMED AT NOTHING.** The benchmark's
gate is the OPSIN round trip, which cannot see preference, and its only other
signal is agreement with PubChem -- whose "IUPAC Name" is generated by a second
engine rather than curated. So a disagreement means two programs differ, and
which one is right is a question about the Blue Book.

This repository has already paid for skipping that step once: the D-022z row
held a pinned expectation nobody had round-tripped, and the "fix" was measured
against a mistake for a month.

What is checked here is the RECORD, not the chemistry: every row carries a
rule, a target, its evidence and the source hash; the engine never appears as
its own authority; and no row points at a corpus label that does not exist.
Whether a verdict is *correct* is not something a test can establish, which is
why each one carries a quotation a reader can check.
"""

from __future__ import annotations

import json
import tomllib
from pathlib import Path

import pytest

BENCH = Path(__file__).resolve().parent.parent / "benchmarks" / "naming"
ADJUDICATION = BENCH / "adjudication.toml"

EXPECTED_SHA = "6b607a40430b95b4370c474d7b7afc5c9906b68c683192fb0c07f9aed3fb563f"

#: The populations whose rows may be adjudicated. heldout_v2 joined in round 5,
#: when it stopped being the fresh population; the current fresh one is never
#: listed here (tests/test_naming_heldout_lock.py).
LABELLED_POPULATIONS = ("corpus.json", "heldout.json", "heldout2.json")

VERDICTS = {
    "ENGINE_WRONG",
    "PUBCHEM_NOT_PREFERRED",
    "BOTH_VALID",
    "BOTH_NOT_PREFERRED",
    "VALID_NO_UNIQUE_PREFERENCE",
    "UNDECIDED",
    # Round 5 (N4): a probe row, with no PubChem string to compare, whose
    # question the book then answered in the engine's favour. BOTH_VALID
    # would assert something about a PubChem name that does not exist.
    "ENGINE_RIGHT",
}


@pytest.fixture(scope="module")
def table() -> dict:
    return tomllib.loads(ADJUDICATION.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def rows(table) -> list[dict]:
    return table["row"]


@pytest.fixture(scope="module")
def rules(table) -> dict[str, dict]:
    """Schema 2: each paragraph quoted once, referenced by `rule_ref`."""
    return {rule["rule_id"]: rule for rule in table.get("rule", [])}


@pytest.fixture(scope="module")
def corpus_labels() -> set[str]:
    labels: set[str] = set()
    for filename in LABELLED_POPULATIONS:
        path = BENCH / filename
        if path.exists():
            labels |= {
                row["label"] for row in json.loads(path.read_text(encoding="utf-8"))
            }
    return labels


def test_the_source_is_pinned_by_hash(table):
    """A P-number outlives the document it points into. The 2013 text has been
    corrected since publication, so the row has to say WHICH revision it was
    decided against."""
    assert table["meta"]["source_sha256"] == EXPECTED_SHA
    assert table["meta"]["source_id"] == "BLUEBOOK_2013_CORRECTED_2022"


def test_every_row_carries_a_verdict_from_the_declared_set(rows):
    unknown = {r["verdict"] for r in rows} - VERDICTS
    assert not unknown, f"verdicts not in the declared set: {unknown}"


def test_every_row_cites_a_rule_and_quotes_its_evidence(rows, rules):
    """The quotation is the part a reader can check. `caffeine` carried a
    P-number for months that had nothing to do with retaining it, which is
    exactly what a citation without a quotation permits.

    A row satisfies this either inline (schema 1: `rule` + `evidence_quote`)
    or through `rule_ref`, every one of which must name a quoted rule."""
    def quoted(r):
        if r.get("rule_ref"):
            return all(rules.get(ref, {}).get("quote", "").strip() for ref in r["rule_ref"])
        return bool(r.get("rule")) and bool(r.get("evidence_quote", "").strip())

    thin = [r["corpus_row_id"] or r.get("case_origin", "?") for r in rows if not quoted(r)]
    assert not thin, f"rows with no rule or no quotation: {thin}"


def test_rule_ids_are_unique_and_every_reference_resolves(table, rows, rules):
    """One quotation per paragraph is the point of schema 2; a duplicate id
    would be two quotations again, and a dangling reference cites nothing."""
    ids = [rule["rule_id"] for rule in table.get("rule", [])]
    assert len(ids) == len(set(ids)), "duplicate rule_id"
    dangling = {ref for r in rows for ref in r.get("rule_ref", []) if ref not in rules}
    assert not dangling, f"rule_refs naming no rule: {dangling}"


def test_every_rule_says_where_in_the_book_it_was_read(rules):
    """A paragraph number is not enough to find a quotation in a 1,500-page
    PDF, and round 3's lookups were slowed by exactly that."""
    unlocated = [rid for rid, rule in rules.items() if not isinstance(rule.get("pdf_page"), int)]
    assert not unlocated, f"rules with no pdf_page: {unlocated}"
    assert all(rule.get("evidence_basis") in ("explicit", "derived") for rule in rules.values())


def test_evidence_is_labelled_explicit_or_derived(rows):
    """Absence of a mention is weaker than a quotation, and rows that lean on
    it say so rather than reading as though the book named the case."""
    bad = [
        r["corpus_row_id"] for r in rows if r.get("evidence_basis") not in
        ("explicit", "derived")
    ]
    assert not bad, f"rows with no evidence_basis: {bad}"


def test_only_undecided_rows_may_lack_a_preferred_target(rows):
    missing = [
        r["corpus_row_id"]
        for r in rows
        if r["verdict"] not in ("UNDECIDED", "VALID_NO_UNIQUE_PREFERENCE")
        and not r.get("preferred_name")
    ]
    assert not missing, f"rows with a verdict but no adjudicated target: {missing}"


def test_the_engine_never_certifies_its_own_output(rows):
    """THE INVARIANT THAT MAKES THE TABLE WORTH ANYTHING. If the engine can be
    cited as the authority, the table degrades into a record of what the engine
    already does."""
    self_certified = [
        r["corpus_row_id"]
        for r in rows
        if "engine" in str(r.get("preferred_name_source", "")).lower()
        or "opsin" in str(r.get("preferred_name_source", "")).lower()
    ]
    assert not self_certified, (
        f"rows citing this engine or its parser as the authority: {self_certified}"
    )


def test_no_row_points_at_a_corpus_label_that_does_not_exist(rows, corpus_labels):
    """A row may legitimately have no corpus label -- `isobutane` comes from
    KNOWN_LIMITATIONS rather than the corpus -- but a NON-EMPTY one has to
    resolve, or the adjudication silently applies to nothing."""
    dangling = [
        r["corpus_row_id"]
        for r in rows
        if r.get("corpus_row_id") and r["corpus_row_id"] not in corpus_labels
    ]
    assert not dangling, f"corpus_row_ids that match no corpus row: {dangling}"


def test_a_row_without_a_corpus_label_says_where_it_came_from(rows):
    orphans = [
        r.get("smiles")
        for r in rows
        if not r.get("corpus_row_id") and not r.get("case_origin")
    ]
    assert not orphans, f"rows with neither a corpus label nor an origin: {orphans}"


def test_the_smiles_matches_the_corpus_row_it_claims(rows, corpus_labels):
    """The adjudication is about a STRUCTURE, not a label. If the corpus row
    is ever re-drawn, this fails rather than letting the verdict transfer to a
    different molecule."""
    from rdkit import Chem

    by_label: dict[str, str] = {}
    for filename in LABELLED_POPULATIONS:
        path = BENCH / filename
        if path.exists():
            for row in json.loads(path.read_text(encoding="utf-8")):
                by_label[row["label"]] = row["smiles"]

    mismatched = []
    for row in rows:
        label = row.get("corpus_row_id")
        if not label or label not in by_label:
            continue
        want = Chem.MolFromSmiles(by_label[label])
        got = Chem.MolFromSmiles(row["smiles"])
        if want is None or got is None:
            mismatched.append(f"{label} (unparsable)")
        elif Chem.MolToSmiles(want) != Chem.MolToSmiles(got):
            mismatched.append(label)
    assert not mismatched, f"adjudication SMILES differs from the corpus row: {mismatched}"


def test_the_completed_classes_are_declared(table):
    """So partial coverage reads as partial. The file adjudicates one class so
    far, and the classes still open are listed at its foot."""
    assert table["meta"]["classes_complete"] == [
        "retained_name_vs_pin",
        "alphanumerical_numbering",
        "retained_parents_substitution",
        "locant_omission",
        "new_pcg_classes",
        "prefix_vocabulary",
        "heldout_v2_disagreements",
        "round4_leftovers",
    ]


def test_every_open_row_says_which_layer_it_fails_in(table, rows):
    """Round 5, N1: "deferred" is not a class. Every row still OPEN or
    UNDECIDED names the layer the defect lives in and the stage expected to
    take it, so an open list can be read by layer rather than as one pile.

    Breaking it: drop `layer` from any OPEN row."""
    layers = set(table["meta"]["layers"])
    stages = {"N2", "N3", "N4", "N5", "N6", "N7", "N8", "later"}
    bad = [
        (r.get("corpus_row_id") or r.get("smiles"), r.get("layer"), r.get("target_stage"))
        for r in rows
        if (r["fix_status"] == "OPEN" or r["verdict"] == "UNDECIDED")
        and (r.get("layer") not in layers or r.get("target_stage") not in stages)
    ]
    assert not bad, bad


def test_an_engine_wrong_row_names_a_target_different_from_the_engine(rows):
    """Breaking the guard: a row that says the engine is wrong but gives the
    engine's own name as the target is a bookkeeping error, and one that would
    make the table look complete while asserting nothing."""
    contradictory = [
        r.get("corpus_row_id") or r.get("case_origin")
        for r in rows
        if r["verdict"] == "ENGINE_WRONG"
        and r.get("preferred_name") == r.get("engine_name")
        and r.get("fix_status") not in ("FIXED", "PARTLY_FIXED")
    ]
    assert not contradictory, (
        "ENGINE_WRONG rows whose target equals the engine's name and which do "
        f"not record that the fix landed: {contradictory}"
    )


def test_the_fix_status_is_a_field_not_prose(rows):
    """An earlier version of the guard above grepped the `note` text for the
    word FIXED, and failed on a row whose note said "now fixed" in lower case.
    A guard that matches its own prose is a shape this repository has recorded
    repeatedly, so the status is a field."""
    allowed = {"FIXED", "PARTLY_FIXED", "OPEN", "NOT_APPLICABLE"}
    bad = [
        (r.get("corpus_row_id") or r.get("case_origin"), r.get("fix_status"))
        for r in rows
        if r.get("fix_status") not in allowed
    ]
    assert not bad, f"rows with no usable fix_status: {bad}"
