"""The shipped nuclide table, and what its generator refuses to build.

`nuclides.json` is generated by `tools/build_nuclide_table.py` from a
COMMITTED NUBASE2020 snapshot. The generator asserts its own invariants at
build time; those same checks run here against the committed file, so a
hand edit is caught even though the generator was not re-run.

The tests that matter most are the qualifier fixtures. A half-life has
eight states and two dimensions, and a parser that flattens any of them
produces a table that looks entirely plausible -- which is the failure
this repository has already recorded twice, from two different PDFs.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path("tools").resolve()))

from build_nuclide_table import (  # noqa: E402
    APPROXIMATE,
    ESTIMATED,
    EXACT,
    LOWER_BOUND,
    PARTICLE_UNSTABLE,
    STABLE,
    UNAVAILABLE,
    UPPER_BOUND,
    _SECONDS,
    parse_half_life,
)

_TABLE = Path("src/openchem/chem/data/nuclides.json")
_SOURCE = Path("src/openchem/chem/data/nubase_4.mas20.txt")


@pytest.fixture(scope="module")
def table() -> dict:
    return json.loads(_TABLE.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def nuclides(table) -> dict:
    return table["nuclides"]


@pytest.fixture(scope="module")
def about(table) -> dict:
    return table["_about"]


# --- the eight states of a half-life ----------------------------------------
#
# One fixture per state, read straight off the source's own columns.
# `parse_half_life(T, unit, dT)`.


@pytest.mark.parametrize(
    "t_field, unit, dt_field, expected_qualifier, expected_seconds",
    [
        ("   4.463  ", "Gy", " 0.003 ", EXACT, 1.408e17),
        ("   2#     ", "ms", "       ", ESTIMATED, 2e-3),
        (" stbl     ", "  ", "       ", STABLE, None),
        ("          ", "  ", "       ", UNAVAILABLE, None),
        ("  >4.6    ", "zs", "       ", LOWER_BOUND, 4.6e-21),
        ("  ~1      ", " s", "       ", APPROXIMATE, 1.0),
        ("  <10     ", "ps", "       ", UPPER_BOUND, 1e-11),
        (" p-unst   ", "  ", "       ", PARTICLE_UNSTABLE, None),
    ],
    ids=["exact", "estimated", "stable", "unavailable",
         "lower_bound", "approximate", "upper_bound", "particle_unstable"],
)
def test_every_half_life_state_survives_the_parse(
    t_field, unit, dt_field, expected_qualifier, expected_seconds
):
    """**A BOUND RENDERED AS A PRECISE HALF-LIFE IS THE FAILURE THIS
    PREVENTS**, and it is the same rule as "an estimated value must not
    read as a measured one" -- applied to four more states."""
    parsed = parse_half_life(t_field, unit, dt_field)

    assert parsed["qualifier"] == expected_qualifier
    if expected_seconds is None:
        assert "seconds" not in parsed
    else:
        assert parsed["seconds"] == pytest.approx(expected_seconds, rel=1e-3)


# --- and the two dimensions, which one qualifier field cannot hold ----------


def test_a_value_and_its_uncertainty_are_recorded_INDEPENDENTLY():
    """`43Al` is an ESTIMATED 4 ms beside a MEASURED >170 ns.

    256 rows carry both. A single qualifier field would force a rule like
    "if dT holds a bound, override the primary qualifier" -- the kind of
    silent precedence that goes wrong later and reads fine until it does.
    """
    parsed = parse_half_life("   4#     ", "ms", ">170ns ")

    assert parsed["qualifier"] == ESTIMATED
    assert parsed["seconds"] == pytest.approx(4e-3)
    assert parsed["uncertainty_qualifier"] == LOWER_BOUND
    assert parsed["uncertainty_s"] == pytest.approx(1.7e-7)


def test_a_half_life_known_ONLY_as_a_bound_takes_that_bound_as_its_value():
    """`18B` has no value at all and `< 26 ns` in the uncertainty column.

    Read as "unavailable" that loses a real measurement, and 38 rows are
    in this position -- a bound expressed where a reader of the value
    column would never look.
    """
    parsed = parse_half_life("          ", "  ", "<26 ns ")

    assert parsed["qualifier"] == UPPER_BOUND
    assert parsed["seconds"] == pytest.approx(2.6e-8)


def test_an_ordinary_uncertainty_carries_no_bound():
    """The control: most `dT` values are a plain uncertainty in the same
    unit as the value, and must not be read as a bound."""
    parsed = parse_half_life("   4.463  ", "Gy", " 0.003 ")

    assert parsed["uncertainty_qualifier"] == EXACT


def test_all_twenty_half_life_units_are_known():
    """A unit table is exactly where one gets quietly truncated, and the
    shortfall then looks like a plausible number rather than an error."""
    for unit in ("ys", "zs", "as", "ps", "ns", "us", "ms", "s",
                 "m", "h", "d", "y", "ky", "My", "Gy", "Ty", "Py", "Ey", "Zy", "Yy"):
        assert unit in _SECONDS

    assert _SECONDS["y"] == pytest.approx(3.156e7, rel=1e-3)
    assert _SECONDS["ys"] < _SECONDS["zs"] < _SECONDS["s"] < _SECONDS["y"] < _SECONDS["Yy"]


# --- ground states only, enforced rather than described ---------------------


def test_the_table_carries_every_state_and_the_counts_reconcile(nuclides, about):
    """**DERIVED AND CHECKED TO ADD UP, never carried as prose.** An
    earlier draft of this work wrote "3557 -> 5684" by hand and left a
    reader wondering which of 5684 and 5685 was the typo. The generator
    counts all five and refuses to build if they do not close.

    This test used to assert the table was ground states ONLY, on the
    reasoning that a molfile cannot express Tc-99m. That reasoning is
    still true and is now a REFUSAL in the write path rather than an
    absence in the data -- the half-life and decay modes of Tc-99m are
    exactly what somebody opens the Isotopes tab to read.
    """
    counts = about["row_counts"]

    assert counts["ground_state_rows"] + counts["isomer_rows"] == counts["source_rows"]
    assert (
        counts["shipped_rows"] == counts["source_rows"] - counts["excluded_rows"]
    )
    assert counts["shipped_rows"] == len(nuclides) == 5684
    assert counts["isomer_rows"] == 2127
    assert counts["excluded_rows"] == 1, "the free neutron, and nothing else"


def test_technetium_99m_is_here_and_says_which_state_it_is(nuclides):
    """The named case, because it is the most-used radionuclide in
    medicine -- and the one a `(Z, A)` key cannot tell from its own
    ground state.

    **THE SUFFIX IS THE SOURCE'S OWN.** NUBASE writes `99Tc m`, so the
    label is read from the name field rather than derived from the index;
    a table mapping 1 to `m` would be a second implementation of somebody
    else's notation.
    """
    assert "43-99" in nuclides, "the ground state"
    metastable = nuclides["43-99-1"]

    assert metastable["state_index"] == 1
    assert metastable["state_label"] == "m"
    assert metastable["half_life"]["seconds"] == pytest.approx(6.0066 * 3600, rel=1e-4)
    assert any(d["mode"] == "IT" for d in metastable["decays"])


def test_tantalum_180m_is_the_one_naturally_occurring_isomer(nuclides):
    """**IT IS MARKED STABLE AND CARRIES AN ABUNDANCE**, which is what
    makes it the fixture every element-level predicate has to be checked
    against: the only isomer in NUBASE that is both."""
    metastable = nuclides["73-180-1"]

    assert metastable["half_life"]["qualifier"] == STABLE
    assert metastable["abundance"] == pytest.approx(0.01201)
    assert nuclides["73-180"]["half_life"]["seconds"] is not None, (
        "and its ground state is NOT stable, which is the inversion"
    )


def test_the_free_neutron_is_not_here(nuclides):
    """NUBASE lists it first, as `1n` with Z=0. It is not an element, and
    every lookup in this application is by element symbol. Found by the
    Z >= 1 invariant refusing to build, which is the invariant working."""
    assert "0-1" not in nuclides
    assert all(entry["z"] >= 1 for entry in nuclides.values())


def test_every_nuclide_is_structurally_possible(nuclides):
    """These establish no science. They catch a column read one field
    over, instantly."""
    for key, entry in nuclides.items():
        assert entry["z"] >= 1, key
        assert entry["a"] >= entry["z"], key
        abundance = entry.get("abundance")
        if abundance is not None:
            assert 0.0 <= abundance <= 100.0, key
        seconds = entry["half_life"].get("seconds")
        if seconds is not None:
            assert seconds > 0, key


def test_every_key_is_its_own_z_and_a_and_state(nuclides):
    """The key is `Z-A` for a ground state and `Z-A-i` for a state above
    it, so a mismatch would make every lookup wrong in a way no
    individual value would reveal.

    **THE STATE PART IS ASSERTED TOO**, because a key that dropped it
    would collide Tc-99m onto Tc-99 -- and a dict silently keeps the last
    one written rather than complaining.
    """
    for key, entry in nuclides.items():
        z, a, *state = key.split("-")
        assert (int(z), int(a)) == (entry["z"], entry["a"])
        assert [str(entry["state_index"])] == state if state else (
            "state_index" not in entry
        ), key


# --- values anybody can check against a textbook ---------------------------


@pytest.mark.parametrize(
    "key, name, seconds, abundance",
    [
        ("92-238", "U-238", 1.4084e17, 99.2742),
        ("84-209", "Po-209", 3.9131e9, None),
        ("6-14", "C-14", 1.7987e11, None),
        ("43-99", "Tc-99", 6.6618e12, None),
        ("6-12", "C-12", None, 98.94),
    ],
)
def test_the_spot_checked_nuclides(nuclides, key, name, seconds, abundance):
    entry = nuclides[key]

    if seconds is not None:
        assert entry["half_life"]["seconds"] == pytest.approx(seconds, rel=1e-3), name
    if abundance is not None:
        assert entry["abundance"] == pytest.approx(abundance, rel=1e-3), name


def test_there_are_exactly_253_stable_GROUND_STATES(nuclides):
    """**253 IS THE TEXTBOOK FIGURE AND 254 IS ALSO CORRECT**, which is
    the whole reason this test now names the population it counts.
    Ta-180m is an isomer marked `stbl`, so a bare count over the table
    gives 254 and reads like an off-by-one against every reference.

    Both are asserted: the ground-state count is the number a reader
    recognises, and the extra one is NAMED rather than tolerated by a
    loosened bound.
    """
    stable = [k for k, e in nuclides.items() if e["half_life"]["qualifier"] == STABLE]
    ground = [k for k in stable if not nuclides[k].get("state_index")]

    assert len(ground) == 253
    assert sorted(set(stable) - set(ground)) == ["73-180-1"], "Ta-180m, and only it"


def test_uranium_238_decays_the_way_the_textbook_says(nuclides):
    """Alpha at 100%, with spontaneous fission and double beta far below
    it -- the branchings, not just the modes."""
    decays = {d["mode"]: d.get("branching") for d in nuclides["92-238"]["decays"]}

    assert decays["A"] == 100.0
    assert decays["SF"] == pytest.approx(5.44e-5)
    assert decays["2B-"] == pytest.approx(2.2e-10)


def test_an_unmeasured_branching_is_marked_rather_than_dropped(nuclides):
    """1,755 branchings carry `?` -- the mode is expected and nobody has
    measured how often. Dropping the qualifier would make it read as a
    measurement; dropping the mode would lose the physics."""
    oganesson = {d["mode"]: d for d in nuclides["118-294"]["decays"]}

    assert "SF" in oganesson
    assert oganesson["SF"].get("qualifier") == "?"
    assert "branching" not in oganesson["SF"]


# --- provenance -------------------------------------------------------------


def test_the_table_records_which_snapshot_it_came_from(table):
    """A hash proves which bytes; a revision proves which scientific
    release. The second answers "why does this disagree with NUBASE2024"."""
    about = table["_about"]

    assert about["source_revision"] == "NUBASE2020"
    assert len(about["source_sha256"]) == 64
    assert about["source_url"].endswith("nubase_4.mas20.txt")
    assert table["_source_key"] == "nubase2020"


def test_the_recorded_hash_is_the_committed_snapshots(table):
    """Otherwise the table could have been generated from anything."""
    import hashlib

    digest = hashlib.sha256(
        _SOURCE.read_text(encoding="utf-8", errors="replace").encode("utf-8")
    ).hexdigest()

    assert table["_about"]["source_sha256"] == digest


def test_the_source_hash_survives_a_line_ending_conversion():
    """**THE TRAP THIS REPOSITORY HAS ALREADY FALLEN INTO ONCE.**

    `core.autocrlf` is true here and there is no `.gitattributes`, so the
    same commit is CRLF in a Windows working tree and LF on a Linux
    runner. A hash over raw BYTES would differ between them and `--check`
    would go red for a reason with nothing to do with content -- which is
    exactly what happened to `build_sources_doc.py`.

    The generator reads with universal newlines, so the text is
    normalised before it is hashed. Asserted rather than assumed.
    """
    import hashlib
    import io

    text = _SOURCE.read_text(encoding="utf-8", errors="replace")
    crlf = text.replace(chr(10), chr(13) + chr(10))
    normalised = io.StringIO(crlf, newline=None).read()

    assert chr(13) not in text
    assert hashlib.sha256(normalised.encode("utf-8")).hexdigest() == hashlib.sha256(
        text.encode("utf-8")
    ).hexdigest()


def test_the_attribution_claims_no_more_than_the_evidence_supports(table):
    """**The article is CC BY 3.0; the data FILE carries a citation
    request.** Those are distinct works, and inferring one licence from
    the other is the provenance mistake this project has spent whole
    commits undoing. The attribution names the article."""
    attribution = table["_about"]["attribution"]

    assert "Creative Commons Attribution 3.0" in attribution
    assert "Chinese Physics C 45, 030001 (2021)" in attribution
    assert "10.1088/1674-1137/abddae" in attribution
    assert "cite the paper" in attribution


def test_abundance_says_which_abundance_it_means(table):
    """It goes straight in front of a reader in the isotope picker."""
    assert "terrestrial" in table["_about"]["abundance_means"]


def test_the_generator_check_passes_against_the_committed_pair():
    """`--check` must never touch the network: CI has no upstream, and a
    NUBASE revision must not turn a run red with nothing in the
    repository having moved."""
    result = subprocess.run(
        [sys.executable, "tools/build_nuclide_table.py", "--check"],
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "match the committed snapshot" in result.stdout


def test_the_state_index_and_the_source_suffix_agree_exactly(nuclides):
    """**THE CHECK THAT SAYS READING THE LABEL FROM THE NAME WAS RIGHT.**

    The suffix is taken from NUBASE's name field rather than derived from
    the index, deliberately -- a table mapping 1 to `m` would be a second
    implementation of somebody else's notation. This measures that the
    two really are one-to-one across all 2,127 states, which is what says
    neither reading is drifting from the other:

        1 m 1372    2 n 460    3 p 155    4 q 38
        5 r 10      6 x   4    8 i  80    9 j  8

    NUBASE's own format header explains the split: `i=1,2` are isomers,
    `i=3,4` levels, `i=8,9` isobaric analogue states -- and it adds that
    3,4,5,6 "can also indicate isomers", which is why nothing here
    branches on the index to decide what a state IS.
    """
    pairs = {}
    for entry in nuclides.values():
        index = entry.get("state_index", 0)
        if index:
            pairs.setdefault(index, set()).add(entry["state_label"])

    assert all(len(labels) == 1 for labels in pairs.values()), pairs
    flat = {index: next(iter(labels)) for index, labels in pairs.items()}
    assert flat == {1: "m", 2: "n", 3: "p", 4: "q", 5: "r", 6: "x", 8: "i", 9: "j"}
    assert len(set(flat.values())) == len(flat), "one suffix per index, both ways"


def test_the_count_reconciliation_is_a_SELF_CHECK_no_input_can_trip():
    """**AN ADMITTED LIMIT, written down rather than papered over.**

    `build` raises if `ground + isomer != source` or if
    `shipped != source - excluded`. Both are unreachable from DATA: every
    parsed row increments exactly one of the two state buckets, and the
    only row the builder drops is the free neutron, which it counts as
    excluded on the way out. So a mutation deleting either raise survives
    every test and always will.

    That is not a hole to fill with a fixture no real file resembles --
    it is the shape of a self-check. What it guards is the next EDIT: a
    `continue` added without a matching count is exactly the mistake that
    would otherwise ship a table quietly one row short. The property is
    asserted here on the shipped counts, and the raise is documented as
    the code assertion it is.
    """
    counts = json.loads(_TABLE.read_text(encoding="utf-8"))["_about"]["row_counts"]

    assert counts["ground_state_rows"] + counts["isomer_rows"] == counts["source_rows"]
    assert counts["shipped_rows"] == counts["source_rows"] - counts["excluded_rows"]
    # And the raise really is in the builder, so deleting it is a visible
    # edit rather than a silent one.
    #
    # **THE FIRST VERSION OF THIS CHECK MATCHED THE PROSE.** "the
    # arithmetic does not close" appears in the module docstring as well
    # as in the message, so deleting the raise left the phrase behind and
    # the mutation survived -- the same trap this project already records
    # for a source scan that flags the comment explaining its own rule.
    # These two fragments occur ONLY in the raised messages.
    source = Path(__file__).resolve().parents[1] / "tools" / "build_nuclide_table.py"
    text = source.read_text(encoding="utf-8")
    assert text.count("shipped from") == 1
    assert text.count("was not read from every row") == 1
