"""The shipped nuclide table, and what its generator refuses to build.

`nuclides.json` is generated by `tools/build_nuclide_table.py` from a
COMMITTED NUBASE2020 snapshot. The generator asserts its own invariants at
build time; those same checks run here against the committed file, so a
hand edit is caught even though the generator was not re-run.

The tests that matter most are the qualifier fixtures. A half-life has
eight states and two dimensions, and a parser that flattens any of them
produces a table that looks entirely plausible -- which is the failure
this repository has already recorded twice, from two different PDFs.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path("tools").resolve()))

from build_nuclide_table import (  # noqa: E402
    APPROXIMATE,
    ESTIMATED,
    EXACT,
    LOWER_BOUND,
    PARTICLE_UNSTABLE,
    STABLE,
    UNAVAILABLE,
    UPPER_BOUND,
    _SECONDS,
    parse_half_life,
)

_TABLE = Path("src/openchem/chem/data/nuclides.json")
_SOURCE = Path("src/openchem/chem/data/nubase_4.mas20.txt")


@pytest.fixture(scope="module")
def table() -> dict:
    return json.loads(_TABLE.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def nuclides(table) -> dict:
    return table["nuclides"]


# --- the eight states of a half-life ----------------------------------------
#
# One fixture per state, read straight off the source's own columns.
# `parse_half_life(T, unit, dT)`.


@pytest.mark.parametrize(
    "t_field, unit, dt_field, expected_qualifier, expected_seconds",
    [
        ("   4.463  ", "Gy", " 0.003 ", EXACT, 1.408e17),
        ("   2#     ", "ms", "       ", ESTIMATED, 2e-3),
        (" stbl     ", "  ", "       ", STABLE, None),
        ("          ", "  ", "       ", UNAVAILABLE, None),
        ("  >4.6    ", "zs", "       ", LOWER_BOUND, 4.6e-21),
        ("  ~1      ", " s", "       ", APPROXIMATE, 1.0),
        ("  <10     ", "ps", "       ", UPPER_BOUND, 1e-11),
        (" p-unst   ", "  ", "       ", PARTICLE_UNSTABLE, None),
    ],
    ids=["exact", "estimated", "stable", "unavailable",
         "lower_bound", "approximate", "upper_bound", "particle_unstable"],
)
def test_every_half_life_state_survives_the_parse(
    t_field, unit, dt_field, expected_qualifier, expected_seconds
):
    """**A BOUND RENDERED AS A PRECISE HALF-LIFE IS THE FAILURE THIS
    PREVENTS**, and it is the same rule as "an estimated value must not
    read as a measured one" -- applied to four more states."""
    parsed = parse_half_life(t_field, unit, dt_field)

    assert parsed["qualifier"] == expected_qualifier
    if expected_seconds is None:
        assert "seconds" not in parsed
    else:
        assert parsed["seconds"] == pytest.approx(expected_seconds, rel=1e-3)


# --- and the two dimensions, which one qualifier field cannot hold ----------


def test_a_value_and_its_uncertainty_are_recorded_INDEPENDENTLY():
    """`43Al` is an ESTIMATED 4 ms beside a MEASURED >170 ns.

    256 rows carry both. A single qualifier field would force a rule like
    "if dT holds a bound, override the primary qualifier" -- the kind of
    silent precedence that goes wrong later and reads fine until it does.
    """
    parsed = parse_half_life("   4#     ", "ms", ">170ns ")

    assert parsed["qualifier"] == ESTIMATED
    assert parsed["seconds"] == pytest.approx(4e-3)
    assert parsed["uncertainty_qualifier"] == LOWER_BOUND
    assert parsed["uncertainty_s"] == pytest.approx(1.7e-7)


def test_a_half_life_known_ONLY_as_a_bound_takes_that_bound_as_its_value():
    """`18B` has no value at all and `< 26 ns` in the uncertainty column.

    Read as "unavailable" that loses a real measurement, and 38 rows are
    in this position -- a bound expressed where a reader of the value
    column would never look.
    """
    parsed = parse_half_life("          ", "  ", "<26 ns ")

    assert parsed["qualifier"] == UPPER_BOUND
    assert parsed["seconds"] == pytest.approx(2.6e-8)


def test_an_ordinary_uncertainty_carries_no_bound():
    """The control: most `dT` values are a plain uncertainty in the same
    unit as the value, and must not be read as a bound."""
    parsed = parse_half_life("   4.463  ", "Gy", " 0.003 ")

    assert parsed["uncertainty_qualifier"] == EXACT


def test_all_twenty_half_life_units_are_known():
    """A unit table is exactly where one gets quietly truncated, and the
    shortfall then looks like a plausible number rather than an error."""
    for unit in ("ys", "zs", "as", "ps", "ns", "us", "ms", "s",
                 "m", "h", "d", "y", "ky", "My", "Gy", "Ty", "Py", "Ey", "Zy", "Yy"):
        assert unit in _SECONDS

    assert _SECONDS["y"] == pytest.approx(3.156e7, rel=1e-3)
    assert _SECONDS["ys"] < _SECONDS["zs"] < _SECONDS["s"] < _SECONDS["y"] < _SECONDS["Yy"]


# --- ground states only, enforced rather than described ---------------------


def test_the_table_is_ground_states_only(nuclides):
    """NUBASE carries isomers too -- 2,285 rows of them. A molfile cannot
    express Tc-99m as distinct from Tc-99, so shipping them would be data
    nothing in this application could reach."""
    assert len(nuclides) == 3557
    assert "43-99" in nuclides, "Tc-99 is a ground state and belongs here"


def test_technetium_99m_is_not_in_the_table(nuclides):
    """The named case, because it is the most-used radionuclide in
    medicine and is exactly what somebody would add by hand."""
    technetium = [key for key in nuclides if key.startswith("43-")]

    assert all(key.count("-") == 1 for key in technetium)
    assert not any("m" in key for key in nuclides)


def test_the_free_neutron_is_not_here(nuclides):
    """NUBASE lists it first, as `1n` with Z=0. It is not an element, and
    every lookup in this application is by element symbol. Found by the
    Z >= 1 invariant refusing to build, which is the invariant working."""
    assert "0-1" not in nuclides
    assert all(entry["z"] >= 1 for entry in nuclides.values())


def test_every_nuclide_is_structurally_possible(nuclides):
    """These establish no science. They catch a column read one field
    over, instantly."""
    for key, entry in nuclides.items():
        assert entry["z"] >= 1, key
        assert entry["a"] >= entry["z"], key
        abundance = entry.get("abundance")
        if abundance is not None:
            assert 0.0 <= abundance <= 100.0, key
        seconds = entry["half_life"].get("seconds")
        if seconds is not None:
            assert seconds > 0, key


def test_every_key_is_its_own_z_and_a(nuclides):
    """The key is `Z-A`, so a mismatch would make every lookup wrong in a
    way no individual value would reveal."""
    for key, entry in nuclides.items():
        z, a = key.split("-")
        assert (int(z), int(a)) == (entry["z"], entry["a"])


# --- values anybody can check against a textbook ---------------------------


@pytest.mark.parametrize(
    "key, name, seconds, abundance",
    [
        ("92-238", "U-238", 1.4084e17, 99.2742),
        ("84-209", "Po-209", 3.9131e9, None),
        ("6-14", "C-14", 1.7987e11, None),
        ("43-99", "Tc-99", 6.6618e12, None),
        ("6-12", "C-12", None, 98.94),
    ],
)
def test_the_spot_checked_nuclides(nuclides, key, name, seconds, abundance):
    entry = nuclides[key]

    if seconds is not None:
        assert entry["half_life"]["seconds"] == pytest.approx(seconds, rel=1e-3), name
    if abundance is not None:
        assert entry["abundance"] == pytest.approx(abundance, rel=1e-3), name


def test_there_are_exactly_253_stable_nuclides(nuclides):
    stable = [k for k, e in nuclides.items() if e["half_life"]["qualifier"] == STABLE]

    assert len(stable) == 253


def test_uranium_238_decays_the_way_the_textbook_says(nuclides):
    """Alpha at 100%, with spontaneous fission and double beta far below
    it -- the branchings, not just the modes."""
    decays = {d["mode"]: d.get("branching") for d in nuclides["92-238"]["decays"]}

    assert decays["A"] == 100.0
    assert decays["SF"] == pytest.approx(5.44e-5)
    assert decays["2B-"] == pytest.approx(2.2e-10)


def test_an_unmeasured_branching_is_marked_rather_than_dropped(nuclides):
    """1,755 branchings carry `?` -- the mode is expected and nobody has
    measured how often. Dropping the qualifier would make it read as a
    measurement; dropping the mode would lose the physics."""
    oganesson = {d["mode"]: d for d in nuclides["118-294"]["decays"]}

    assert "SF" in oganesson
    assert oganesson["SF"].get("qualifier") == "?"
    assert "branching" not in oganesson["SF"]


# --- provenance -------------------------------------------------------------


def test_the_table_records_which_snapshot_it_came_from(table):
    """A hash proves which bytes; a revision proves which scientific
    release. The second answers "why does this disagree with NUBASE2024"."""
    about = table["_about"]

    assert about["source_revision"] == "NUBASE2020"
    assert len(about["source_sha256"]) == 64
    assert about["source_url"].endswith("nubase_4.mas20.txt")
    assert table["_source_key"] == "nubase2020"


def test_the_recorded_hash_is_the_committed_snapshots(table):
    """Otherwise the table could have been generated from anything."""
    import hashlib

    digest = hashlib.sha256(
        _SOURCE.read_text(encoding="utf-8", errors="replace").encode("utf-8")
    ).hexdigest()

    assert table["_about"]["source_sha256"] == digest


def test_the_source_hash_survives_a_line_ending_conversion():
    """**THE TRAP THIS REPOSITORY HAS ALREADY FALLEN INTO ONCE.**

    `core.autocrlf` is true here and there is no `.gitattributes`, so the
    same commit is CRLF in a Windows working tree and LF on a Linux
    runner. A hash over raw BYTES would differ between them and `--check`
    would go red for a reason with nothing to do with content -- which is
    exactly what happened to `build_sources_doc.py`.

    The generator reads with universal newlines, so the text is
    normalised before it is hashed. Asserted rather than assumed.
    """
    import hashlib
    import io

    text = _SOURCE.read_text(encoding="utf-8", errors="replace")
    crlf = text.replace(chr(10), chr(13) + chr(10))
    normalised = io.StringIO(crlf, newline=None).read()

    assert chr(13) not in text
    assert hashlib.sha256(normalised.encode("utf-8")).hexdigest() == hashlib.sha256(
        text.encode("utf-8")
    ).hexdigest()


def test_the_attribution_claims_no_more_than_the_evidence_supports(table):
    """**The article is CC BY 3.0; the data FILE carries a citation
    request.** Those are distinct works, and inferring one licence from
    the other is the provenance mistake this project has spent whole
    commits undoing. The attribution names the article."""
    attribution = table["_about"]["attribution"]

    assert "Creative Commons Attribution 3.0" in attribution
    assert "Chinese Physics C 45, 030001 (2021)" in attribution
    assert "10.1088/1674-1137/abddae" in attribution
    assert "cite the paper" in attribution


def test_abundance_says_which_abundance_it_means(table):
    """It goes straight in front of a reader in the isotope picker."""
    assert "terrestrial" in table["_about"]["abundance_means"]


def test_the_generator_check_passes_against_the_committed_pair():
    """`--check` must never touch the network: CI has no upstream, and a
    NUBASE revision must not turn a run red with nothing in the
    repository having moved."""
    result = subprocess.run(
        [sys.executable, "tools/build_nuclide_table.py", "--check"],
        capture_output=True,
        text=True,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "match the committed snapshot" in result.stdout
