# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller one-directory build of OpenChem Studio.

Run it through `build.ps1` at the repository root rather than invoking
`pyinstaller` by hand; that script checks prerequisites and stages the
`plugins/` tree afterwards.

WHY PYINSTALLER AND NOT NUITKA. The scaffolding this replaced was a Nuitka
template. The deciding factor is not output quality -- Nuitka's would be
better -- but that almost every failure mode here is a *missing data file*
that produces a silently blank window rather than a build error, so the
build/launch/see-what-is-blank cycle gets run many times. PyInstaller's
cycle is minutes where Nuitka's is tens of minutes, and its PySide6 +
QtWebEngine hooks are far better trodden. Startup speed is not this
application's bottleneck.

EVERY `datas` ENTRY BELOW IS THERE BECAUSE SOMETHING BREAKS WITHOUT IT, and
mostly breaks *silently*. Each one says what. Do not prune this list by
inspection -- prune it by removing an entry and launching the exe.
"""

from pathlib import Path

from PyInstaller.utils.hooks import collect_data_files, collect_submodules

ROOT = Path(SPECPATH).parent  # noqa: F821 -- SPECPATH is injected by PyInstaller
PKG = ROOT / "src" / "openchem"

# --------------------------------------------------------------------------
# Data files
# --------------------------------------------------------------------------
datas = []

# The three web views. Ketcher (2D editor), Mol* (macromolecules) and 3Dmol
# (small-molecule 3D) are all loaded as local HTML off disk by
# ui/widgets/*_backend.py, each resolving `Path(__file__)/../../../resources`.
# Frozen, that resolves inside `_internal/openchem/`, so mirroring the source
# layout under `openchem/resources` needs no code change. Miss this and the
# app starts perfectly and every editor/viewer is a blank white rectangle.
datas += [(str(PKG / "resources"), "openchem/resources")]

# The vendored IUPAC namer's data, which MUST land as a SIBLING of
# `vendor/iupac_namer/`, not inside it. Different modules resolve it from
# different depths -- `data_loader.py` walks up two levels,
# `perception/fg/acid_infix_composition.py` walks up four -- so any freezer
# that flattens package data breaks naming. This was already got wrong once
# during vendoring; see src/openchem/vendor/VENDORING.md.
datas += [(str(PKG / "vendor" / "data"), "openchem/vendor/data")]

# The user-facing documentation, which IS the in-application help --
# `openchem/help.py` renders docs/USER_GUIDE.md and friends directly so a
# documentation pass updates the help window with no second copy to
# maintain. `docs/` lives beside `src/`, not inside the package, so unlike
# every other entry here it cannot simply mirror its source path; it is
# mapped to `openchem/docs`, which is the first location
# `help.docs_directory()` looks in. Miss this and Help opens an empty
# window in the frozen build while working perfectly from a checkout.
datas += [(str(ROOT / "docs"), "openchem/docs")]

# The regulatory rulesets. Only `generated/` is shipped: `sources/` is the
# hand-edited input to `tools/build_regulatory_rulesets.py` and is of no use
# to a frozen application, while shipping both would invite someone to edit
# the copy that is never read. Miss this and the regulatory engine loads
# zero rulesets and reports "nothing was checked" -- honest, and useless.
datas += [
    (
        str(PKG / "chem" / "data" / "regulatory" / "generated"),
        "openchem/chem/data/regulatory/generated",
    )
]

# The structure checker's hypervalent-valence exceptions. Named as a FILE
# rather than shipping `chem/data` wholesale, because the line above
# deliberately ships only part of that tree -- a directory entry here would
# quietly start shipping `regulatory/sources/` too, which the comment above
# explains is exactly what should not happen.
#
# Miss this and the valence checker raises FileNotFoundError the first time
# anyone draws a structure in the frozen app, having worked perfectly from a
# checkout. Same failure shape as `admet_runner.py` two blocks down.
datas += [(str(PKG / "chem" / "data" / "hypervalent_rules.json"), "openchem/chem/data")]

# The oxidation-state electronegativity table, for the same reason and with
# the same failure mode: it works from a checkout and raises
# FileNotFoundError in the frozen app the first time anybody asks.
datas += [(str(PKG / "chem" / "data" / "electronegativity.json"), "openchem/chem/data")]

# The periodic-table reference. Generated by tools/build_element_reference.py
# and committed; the dialog reads it at open time and would show an empty
# table without it.
datas += [(str(PKG / "chem" / "data" / "elements.json"), "openchem/chem/data")]

# Drago-Wayland E and C parameters. Generated by
# tools/build_lewis_parameters.py and committed. Unlike the files above,
# this one is OPTIONAL by design -- `lewis_adduct.parameter_table` returns
# an empty table when it is absent, and everything except the kcal/mol
# line of evidence still works. Shipping it anyway, because a frozen build
# silently losing the only real energy in that panel is not a trade-off
# anyone chose.
datas += [(str(PKG / "chem" / "data" / "lewis_parameters.json"), "openchem/chem/data")]

# Scripts that are never imported -- they are handed as argv to a *sidecar*
# interpreter (the pkasolver and ADMET environments, which run their own
# Python, not ours). PyInstaller's import analysis therefore never sees them,
# and they have to ship as plain source next to their callers, which locate
# them with `Path(__file__).resolve().parent / "..._runner.py"`.
#
# KEEP THIS LIST IN STEP WITH `chem/*_runner.py`. Both ways of being wrong
# have already happened here: a `stout_runner.py` entry outlived the file
# (STOUT was removed, and a missing `datas` source aborts the build), while
# `admet_runner.py` was added to the app and never added here -- which does
# not fail the build at all, it fails the first time a user opens an ADMET
# calculator in the frozen app.
datas += [
    (str(PKG / "chem" / "pka_runner.py"), "openchem/chem"),
    (str(PKG / "chem" / "admet_runner.py"), "openchem/chem"),
]

# RDKit's own data: the atomic-properties table, ring templates and the
# SMARTS catalogues behind fragment/functional-group perception. RDKit finds
# them via RDDataDir and raises at *call* time, not import time.
datas += collect_data_files("rdkit")

# Contrib/SA_Score/sascorer.py, which is SOURCE that behaves as data. The
# synthetic-accessibility descriptor appends `RDConfig.RDContribDir/SA_Score`
# to sys.path and imports `sascorer` by name at call time
# (chem/descriptor_providers.py), so the analysis never sees the import and
# `collect_data_files` skips it -- that helper excludes .py files by default,
# which is why the line above collects the neighbouring fpscores.pkl.gz and
# not the one module that reads it. Caught only by launching the build: every
# Physicochemical property in the Properties panel read
# "No module named 'sascorer'", because one failing provider takes the whole
# rdkit descriptor batch down with it.
datas += collect_data_files(
    "rdkit", include_py_files=True, includes=["Contrib/SA_Score/*.py"]
)

# py2opsin ships OPSIN as a 14 MB jar beside its module and shells out to
# `java -jar` against it. It is data, not an import. (The JRE itself is a
# user-installed sidecar and is deliberately NOT bundled.)
datas += collect_data_files("py2opsin")

# Open Babel's format plugins (*.obf) and its data tables. Every file format
# Open Babel reads or writes lives in one of these nine plugin libraries --
# they are dlopen'd by Open Babel's own plugin loader at import time, so
# PyInstaller's binary analysis never sees them and collected only
# `bin/openbabel-3.dll`.
#
# WHY `bin/` AND NOT WHERE THE PACKAGE SAYS. `openbabel/__init__.py` sets
# BABEL_LIBDIR to `<pkg>/lib/openbabel/3.1.0` and BABEL_DATADIR to
# `<pkg>/share/openbabel/3.1.0` -- and the wheel HAS NO `lib/` DIRECTORY AT
# ALL. Both env vars point at paths that do not exist, and Open Babel falls
# back to looking beside its own DLL, which is `bin/`. That fallback is what
# actually works in a source checkout, so the frozen build has to reproduce
# `bin/` faithfully rather than trust the documented variables.
#
# Missing, this fails in one specific place and nowhere else: `pybel` is
# imported lazily inside `docking_providers.dock()`, and with no format
# plugins `GetSupportedInputFormat()` returns entries that pybel's
# `_formatstodict` cannot split, so DOCKING dies with
# "ValueError: not enough values to unpack (expected 2, got 1)" -- an error
# that mentions neither Open Babel nor a missing file. Everything else in the
# application keeps working.
datas += collect_data_files(
    "openbabel", includes=["bin/*.obf", "bin/data/*", "share/**"]
)

# --------------------------------------------------------------------------
# Hidden imports
# --------------------------------------------------------------------------
# Whole-package sweep of our own code. Panels, providers and the naming
# engine's perception modules are reached through registries and dynamic
# dispatch rather than literal top-level imports, so static analysis misses
# a large fraction of them, and each miss is a feature that raises
# ImportError only once a user clicks the thing.
hiddenimports = collect_submodules("openchem")

# The AI-assistant plugin imports these lazily, inside the request functions,
# so they are invisible to the analysis twice over: the plugin tree is never
# statically imported at all, and the import is not at module level. A frozen
# app has no pip, so a user cannot install them afterwards the way the
# error message ("run: uv sync --extra ai") assumes -- if they ship at all,
# they ship here.
hiddenimports += ["anthropic", "openai", "requests"]

a = Analysis(  # noqa: F821
    [str(ROOT / "packaging" / "openchem_launcher.py")],
    pathex=[str(ROOT / "src")],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    # tkinter is pulled in by matplotlib-adjacent transitive imports and is
    # ~10 MB of Tcl/Tk this application never uses; pytest has no business in
    # a shipped build.
    excludes=["tkinter", "pytest", "_pytest"],
    noarchive=False,
    optimize=0,
)

# --------------------------------------------------------------------------
# Qt translation trimming -- the one safe size win
# --------------------------------------------------------------------------
# PySide6 ships ~62 MB of translations. Two distinct sets live in there and
# they are NOT equally droppable:
#
#   translations/*.qm                  Qt's own UI strings for ~40 locales.
#                                      This app has no translations, so these
#                                      only ever localise stock Qt dialogs.
#                                      Safe to drop.
#   translations/qtwebengine_locales/  Chromium's locale packs. QtWebEngine
#                                      refuses to initialise without the one
#                                      matching its locale, so dropping ALL
#                                      of these is one of the ways to get
#                                      three blank web views. en-US is kept.
def _keep(entry):
    dest = entry[0].replace("\\", "/")
    if "/qtwebengine_locales/" in dest:
        return dest.endswith("en-US.pak")
    return not dest.endswith(".qm")


a.datas = [entry for entry in a.datas if _keep(entry)]

pyz = PYZ(a.pure)  # noqa: F821

exe = EXE(  # noqa: F821
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="OpenChemStudio",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,  # UPX corrupts Qt DLLs often enough that it is not worth it.
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(ROOT / "icon.ico") if (ROOT / "icon.ico").exists() else None,
)

coll = COLLECT(  # noqa: F821
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="OpenChemStudio",
)
