"""Builds the ordinary-compound battery (naming round 9, B2) from `battery_r9_protocol.toml`.

B2 is discovery and regression, never a preference oracle (see the protocol file's own header): no row
built here ever becomes a preferred-name target. Every row instead carries how its structure was obtained,
so a later reader can tell "built by rule" (ground truth by construction) from "resolved by name" (only as
trustworthy as two independent lookups agreeing).

## Use

    python tools/naming_battery_build.py generate     # rule-based categories only, no network
    python tools/naming_battery_build.py resolve      # name-based categories: PubChem + OPSIN, needs network
    python tools/naming_battery_build.py chembl       # the ChEMBL max_phase=4 sample, needs network
    python tools/naming_battery_build.py assemble     # merge everything into benchmarks/naming/battery_r9.toml

Each subcommand writes its own scratch JSON under `benchmarks/naming/battery_scratch/` (gitignored data, not
committed) so a slow network step never has to be redone because a later step failed; `assemble` is the only
one that writes the committed file.
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BENCH = ROOT / "benchmarks" / "naming"
PROTOCOL = BENCH / "battery_r9_protocol.toml"
SCRATCH = BENCH / "battery_scratch"

sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(Path(__file__).resolve().parent))


def protocol_sha256() -> str:
    return hashlib.sha256(PROTOCOL.read_bytes()).hexdigest()


def load_protocol() -> dict:
    import tomllib

    return tomllib.loads(PROTOCOL.read_text(encoding="utf-8"))


# =====================================================================================================
# Rule-based generation: functional-group pairs. No lookup -- the SMILES IS the ground truth.
# =====================================================================================================

#: Every group's attachment fragment, split into what precedes ("before") and what follows ("after") the
#: propane-1,3-diyl backbone "CCC", so `before(A) + "CCC" + after(B)` is always a single valid SMILES for
#: the pair (A at C1, B at C3). Chosen so every fragment is a MINIMAL, unambiguous representative of its
#: group -- e.g. "ester" and "ether" use a methyl cap because a bare alkoxy/acyloxy needs a second carbon
#: to be a real ester/ether rather than a hydroxyl/alkoxide.
_GROUP_FRAGMENTS: dict[str, tuple[str, str]] = {
    "hydroxyl": ("O", "O"),
    "primary_amine": ("N", "N"),
    "carboxylic_acid": ("OC(=O)", "C(=O)O"),
    "ester": ("COC(=O)", "C(=O)OC"),
    "primary_amide": ("NC(=O)", "C(=O)N"),
    "nitrile": ("N#C", "C#N"),
    "chloro": ("Cl", "Cl"),
    "ether": ("CO", "OC"),
    "ketone": ("CC(=O)", "C(=O)C"),
    "aldehyde": ("O=C", "C=O"),
    "nitro": ("[O-][N+](=O)", "[N+](=O)[O-]"),
    "thiol": ("S", "S"),
}

_FALLBACK_BACKBONE = "CCCCCC"  # hexane-1,6-diyl, logged when used


def generate_functional_group_pairs(groups: list[str]) -> list[dict]:
    from rdkit import Chem

    missing = [g for g in groups if g not in _GROUP_FRAGMENTS]
    if missing:
        raise SystemExit(f"no fragment defined for group(s): {missing}")

    rows = []
    for a, b in itertools.combinations(groups, 2):
        before_a, _ = _GROUP_FRAGMENTS[a]
        _, after_b = _GROUP_FRAGMENTS[b]
        scaffold = "CCC"
        smiles = f"{before_a}{scaffold}{after_b}"
        mol = Chem.MolFromSmiles(smiles)
        used_fallback = False
        if mol is None:
            # The escape hatch the protocol promises: try the longer backbone before giving up.
            used_fallback = True
            scaffold = _FALLBACK_BACKBONE
            smiles = f"{before_a}{scaffold}{after_b}"
            mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            raise SystemExit(f"functional_group_pairs: could not build a structure for ({a}, {b}): {smiles!r}")
        canonical = Chem.MolToSmiles(mol)
        rows.append(
            {
                "label": f"fgp-{a}+{b}",
                "category": "functional_group_pairs",
                "smiles": canonical,
                "source": "generated by rule",
                "provenance": {"groups": [a, b], "scaffold": "propane-1,3-diyl" if not used_fallback else "hexane-1,6-diyl (fallback)"},
            }
        )
    return rows


# =====================================================================================================
# Rule-based generation: salts. No lookup -- charge-balanced multi-component SMILES built directly.
# =====================================================================================================

_ION_SMILES: dict[str, tuple[str, int]] = {
    # name -> (SMILES, charge)
    "Na+": ("[Na+]", 1),
    "K+": ("[K+]", 1),
    "NH4+": ("[NH4+]", 1),
    "Ca2+": ("[Ca+2]", 2),
    "Mg2+": ("[Mg+2]", 2),
    "Fe3+": ("[Fe+3]", 3),
    "Cl-": ("[Cl-]", -1),
    "Br-": ("[Br-]", -1),
    "NO3-": ("[N+](=O)([O-])[O-]", -1),
    "SO4_2-": ("[O-]S(=O)(=O)[O-]", -2),
    "CO3_2-": ("[O-]C(=O)[O-]", -2),
    "PO4_3-": ("[O-]P(=O)([O-])[O-]", -3),
}

#: Only these reduced cation:anion ratios are built -- a genuine restriction, not an oversight: the
#: protocol commits to it before any salt is generated, so a combination needing e.g. 1:3 (FeCl3) is
#: dropped and counted rather than silently included with a different ratio rule applied after the fact.
_ALLOWED_RATIOS = {(1, 1), (1, 2), (2, 1)}


def _reduced_ratio(cation_charge: int, anion_charge: int) -> tuple[int, int]:
    import math

    a, c = abs(anion_charge), abs(cation_charge)
    g = math.gcd(a, c)
    return (a // g, c // g)  # (n_cations, n_anions)


def generate_salts(cations: list[str], anions: list[str]) -> tuple[list[dict], list[dict]]:
    from rdkit import Chem

    rows, dropped = [], []
    for cation_name, anion_name in itertools.product(cations, anions):
        cation_smiles, cation_charge = _ION_SMILES[cation_name]
        anion_smiles, anion_charge = _ION_SMILES[anion_name]
        n_cation, n_anion = _reduced_ratio(cation_charge, anion_charge)
        if (n_cation, n_anion) not in _ALLOWED_RATIOS:
            dropped.append(
                {
                    "cation": cation_name, "anion": anion_name,
                    "reason": f"needs a {n_cation}:{n_anion} ratio, outside {{1:1, 1:2, 2:1}}",
                }
            )
            continue
        smiles = ".".join([cation_smiles] * n_cation + [anion_smiles] * n_anion)
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            raise SystemExit(f"salts: could not build {cation_name}/{anion_name}: {smiles!r}")
        canonical = Chem.MolToSmiles(mol)
        rows.append(
            {
                "label": f"salt-{cation_name}+{anion_name}",
                "category": "salts",
                "smiles": canonical,
                "source": "generated by rule",
                "provenance": {"cation": cation_name, "anion": anion_name, "ratio": f"{n_cation}:{n_anion}"},
            }
        )
    return rows, dropped


def cmd_generate(_args: argparse.Namespace) -> None:
    protocol = load_protocol()
    SCRATCH.mkdir(parents=True, exist_ok=True)

    fgp = generate_functional_group_pairs(protocol["category"]["functional_group_pairs"]["groups"])
    (SCRATCH / "functional_group_pairs.json").write_text(json.dumps(fgp, indent=1), encoding="utf-8")
    print(f"functional_group_pairs: {len(fgp)} rows -> {SCRATCH / 'functional_group_pairs.json'}")

    salt_cfg = protocol["category"]["salts"]
    salts, dropped = generate_salts(salt_cfg["cations"], salt_cfg["anions"])
    (SCRATCH / "salts.json").write_text(json.dumps(salts, indent=1), encoding="utf-8")
    (SCRATCH / "salts_dropped.json").write_text(json.dumps(dropped, indent=1), encoding="utf-8")
    print(f"salts: {len(salts)} rows ({len(dropped)} combinations dropped for ratio) -> {SCRATCH / 'salts.json'}")
    expected = salt_cfg["count"]
    if len(salts) != expected:
        print(
            f"  NOTE: protocol says count={expected}, generator produced {len(salts)}. "
            f"Update battery_r9_protocol.toml's [category.salts].count to match -- this is the actual, "
            f"computed charge-balance result, not a target to force the generator toward.",
            file=sys.stderr,
        )


# =====================================================================================================
# Rule-based generation: dipeptides. Built by rule, not looked up (protocol [category.amino_acids_and_peptides]).
# =====================================================================================================

#: Standard L-amino-acid side chains, as the fragment attached to the alpha carbon: `N[C@@H](R)C(=O)O`.
#: Glycine has no side chain (achiral alpha carbon) and proline's amino group is part of its own ring, so
#: both are handled separately below rather than forced into this shape. Internal stereocenters on
#: isoleucine and threonine's side chains are left unspecified -- this is a naming FIXTURE, not a claim
#: about which diastereomer; only the alpha carbon's L-configuration is asserted.
_SIDE_CHAINS: dict[str, str] = {
    "alanine": "C",
    "valine": "C(C)C",
    "leucine": "CC(C)C",
    "isoleucine": "C(C)CC",
    "phenylalanine": "Cc1ccccc1",
    "tryptophan": "Cc1c[nH]c2ccccc12",
    "methionine": "CCSC",
    "serine": "CO",
    "threonine": "C(O)C",
    "cysteine": "CS",
    "tyrosine": "Cc1ccc(O)cc1",
    "asparagine": "CC(N)=O",
    "glutamine": "CCC(N)=O",
    "aspartic acid": "CC(=O)O",
    "glutamic acid": "CCC(=O)O",
    "lysine": "CCCCN",
    "arginine": "CCCNC(=N)N",
    "histidine": "Cc1c[nH]cn1",
}

_PROLINE_AS_FIRST = "N1CCC[C@H]1C(=O)"     # ring N is already the free N-terminus; ends ready for the peptide bond
_PROLINE_AS_SECOND = "N1CCC[C@H]1C(=O)O"   # ring N becomes the amide nitrogen when concatenated after residue 1


def _residue_fragment(name: str, *, first: bool) -> str:
    if name == "glycine":
        return "NCC(=O)" if first else "NCC(=O)O"
    if name == "proline":
        return _PROLINE_AS_FIRST if first else _PROLINE_AS_SECOND
    side_chain = _SIDE_CHAINS[name]
    return f"N[C@@H]({side_chain})C(=O)" if first else f"N[C@@H]({side_chain})C(=O)O"


def generate_dipeptides(amino_acid_names: list[str], count: int, seed: int) -> list[dict]:
    """`count` seeded, unordered pairs from `amino_acid_names`, each built into a dipeptide by forming the
    peptide bond programmatically (residue 1's carbonyl to residue 2's amino nitrogen) -- never looked up."""
    import random

    from rdkit import Chem

    rng = random.Random(seed)
    pairs = list(itertools.combinations(sorted(amino_acid_names), 2))
    chosen = rng.sample(pairs, min(count, len(pairs)))

    rows = []
    for a, b in chosen:
        smiles = _residue_fragment(a, first=True) + _residue_fragment(b, first=False)
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            raise SystemExit(f"dipeptides: could not build {a}-{b}: {smiles!r}")
        rows.append(
            {
                "label": f"dipeptide-{a}+{b}",
                "category": "amino_acids_and_peptides",
                "smiles": Chem.MolToSmiles(mol),
                "source": "generated by rule (peptide bond formed programmatically)",
                "provenance": {"residues": [a, b]},
            }
        )
    return rows


def cmd_dipeptides(_args: argparse.Namespace) -> None:
    protocol = load_protocol()
    SCRATCH.mkdir(parents=True, exist_ok=True)
    # Same 20 names the protocol lists for resolving -- see _AMINO_ACID_NAMES below.
    count = protocol["category"]["amino_acids_and_peptides"]["count"] - 20  # 40 total - 20 standalone AAs
    seed = 20260922
    rows = generate_dipeptides(_AMINO_ACID_NAMES, count, seed)
    (SCRATCH / "dipeptides.json").write_text(json.dumps(rows, indent=1), encoding="utf-8")
    print(f"dipeptides: {len(rows)} rows (seed {seed}) -> {SCRATCH / 'dipeptides.json'}")


# =====================================================================================================
# Name resolution: PubChem + OPSIN, two STRUCTURE services (never nomenclature authorities). Agreement
# gives fixture-structure confidence and nothing more -- see the protocol's [resolvers] section.
# =====================================================================================================

#: The 20 proteinogenic amino acids, by their common name -- both resolvers recognise these directly.
_AMINO_ACID_NAMES = [
    "glycine", "alanine", "valine", "leucine", "isoleucine", "proline", "phenylalanine",
    "tryptophan", "methionine", "serine", "threonine", "cysteine", "tyrosine", "asparagine",
    "glutamine", "aspartic acid", "glutamic acid", "lysine", "arginine", "histidine",
]


def _solvent_names() -> list[str]:
    data = json.loads((ROOT / "src" / "openchem" / "chem" / "data" / "abraham_solvents.json").read_text(encoding="utf-8"))
    return sorted(data["solvents"].keys())


def _canonical(smiles: str):
    from rdkit import Chem

    mol = Chem.MolFromSmiles(smiles)
    return Chem.MolToSmiles(mol) if mol is not None else None


#: 1.0s between PubChem calls -- NCBI's usage policy asks for no more than 5 requests/second, but a
#: sustained run of 150+ calls at 0.34s pacing hit HTTP 503 partway through and stayed there for the rest
#: of the run (measured 2026-09-22: reagents, sugars, vitamins and dyes all came back 0% resolved; a fresh
#: call minutes later, outside the batch, succeeded at once). PubChem's own throttling is stricter under
#: sustained load than the per-second guidance alone suggests, and treating a transient 503 as "this
#: compound doesn't resolve" would be a wrong result recorded as if it were a real one -- see the retry
#: below, which is the actual fix; the wider pacing just makes it fire less often.
_PUBCHEM_PACING_SECONDS = 1.0

#: A 503 is retried with backoff, never silently recorded as RESOLVER_AMBIGUOUS -- a server being
#: temporarily overloaded is not a claim about whether the compound resolves.
_PUBCHEM_MAX_RETRIES = 4
_PUBCHEM_RETRY_BASE_SECONDS = 5.0


def _pubchem_lookup_with_retry(name: str):
    """`pubchem_structure_for_name`, retrying a 503 with backoff. Raises NamingError for anything else,
    including a 503 that never clears within the retry budget."""
    import time

    from openchem.chem import naming_providers as np

    last_exc: np.NamingError | None = None
    for attempt in range(_PUBCHEM_MAX_RETRIES + 1):
        try:
            return np.pubchem_structure_for_name(name)
        except np.NamingError as exc:
            last_exc = exc
            if "503" not in str(exc) or attempt == _PUBCHEM_MAX_RETRIES:
                raise
            delay = _PUBCHEM_RETRY_BASE_SECONDS * (2**attempt)
            print(f"    (PubChem 503 on {name!r}, retry {attempt + 1}/{_PUBCHEM_MAX_RETRIES} after {delay:.0f}s)", file=sys.stderr)
            time.sleep(delay)
    raise last_exc  # pragma: no cover - unreachable, loop always returns or raises


def _formula(smiles: str) -> str | None:
    from rdkit import Chem
    from rdkit.Chem import rdMolDescriptors

    mol = Chem.MolFromSmiles(smiles)
    return rdMolDescriptors.CalcMolFormula(mol) if mol is not None else None


def _opsin_confirms(pubchem_canonical: str) -> tuple[bool, str | None]:
    """OPSIN could not parse the INPUT common name (e.g. 'indigo', 'thiamine' -- OPSIN is a grammar for
    systematic names, not a dictionary of trivial or trade names, however standard they are among
    chemists). Ask PubChem for its OWN computed IUPAC name for the structure it found, then check OPSIN
    parses THAT back to the same structure -- genuine independent confirmation that does not require
    OPSIN to know a name it structurally cannot. Returns (confirmed, pubchem_iupac_name_or_None)."""
    from rdkit import Chem

    from openchem.chem import naming_providers as np

    mol = Chem.MolFromSmiles(pubchem_canonical)
    if mol is None:
        return False, None
    try:
        iupac = np.pubchem_name_for_structure(mol)
    except np.NamingError:
        return False, None
    opsin_of_pubchem_name = np.opsin_structures_for_names([iupac.name])[0]
    if opsin_of_pubchem_name is None:
        return False, iupac.name
    return _canonical(opsin_of_pubchem_name.smiles) == pubchem_canonical, iupac.name


def resolve_names(category: str, names: list[str]) -> tuple[list[dict], list[dict]]:
    """PubChem (one call per name, paced, retried on 503) + OPSIN (one batch call for all names).

    Two things beyond a plain string comparison, both found live and both principled rather than
    per-category patches (see the module docstring's history for the measurements):
      1. Same molecular FORMULA but a different canonical SMILES is a tautomer or ring-form choice
         (D-glucose: OPSIN gives the open-chain aldehyde, PubChem the cyclic pyranose -- same compound,
         same formula, different valid representation), never a genuinely different compound. Kept, noted.
      2. OPSIN failing to parse the INPUT name at all (trivial/trade names like 'indigo' or 'thiamine' are
         outside its grammar) falls back to `_opsin_confirms`: PubChem's own computed IUPAC name for the
         structure it found, re-verified by OPSIN. Kept, noted, if that confirms; RESOLVER_AMBIGUOUS if not.
    """
    import time

    from openchem.chem import naming_providers as np

    print(f"  {category}: resolving {len(names)} names through OPSIN (one JVM start)...", file=sys.stderr)
    opsin_results = np.opsin_structures_for_names(names)

    rows, dropped = [], []
    for i, name in enumerate(names):
        if i > 0:
            time.sleep(_PUBCHEM_PACING_SECONDS)
        opsin = opsin_results[i]
        opsin_canonical = _canonical(opsin.smiles) if opsin else None

        try:
            pubchem = _pubchem_lookup_with_retry(name)
            pubchem_canonical = _canonical(pubchem.smiles)
        except np.NamingError as exc:
            pubchem_canonical = None
            pubchem_error = str(exc)
        else:
            pubchem_error = None

        note = None
        if pubchem_canonical is None:
            outcome = f"RESOLVER_AMBIGUOUS: PubChem: {pubchem_error}" if pubchem_error else "RESOLVER_AMBIGUOUS: PubChem returned no structure"
            dropped.append({"name": name, "outcome": "RESOLVER_AMBIGUOUS", "reason": outcome})
        elif opsin_canonical == pubchem_canonical:
            outcome = "MATCH"
        elif opsin_canonical is not None and _formula(opsin_canonical) == _formula(pubchem_canonical):
            outcome = "MATCH (same formula, different tautomer/ring-form)"
            note = f"OPSIN gave {opsin_canonical!r}; kept PubChem's {pubchem_canonical!r} (same molecular formula)"
        elif opsin_canonical is None:
            confirmed, pubchem_iupac = _opsin_confirms(pubchem_canonical)
            if confirmed:
                outcome = "MATCH (via PubChem's own IUPAC name, OPSIN-confirmed)"
                note = f"OPSIN could not parse {name!r} directly; confirmed via PubChem's name {pubchem_iupac!r}"
            else:
                outcome = "RESOLVER_AMBIGUOUS: OPSIN could not parse this name, and could not confirm PubChem's own IUPAC name for it either"
                dropped.append({"name": name, "outcome": "RESOLVER_AMBIGUOUS", "reason": outcome, "pubchem_iupac_name": pubchem_iupac})
        else:
            outcome = "RESOLVER_DISAGREE"
            dropped.append(
                {
                    "name": name, "outcome": "RESOLVER_DISAGREE",
                    "opsin_smiles": opsin_canonical, "pubchem_smiles": pubchem_canonical,
                }
            )

        if outcome.startswith("MATCH"):
            provenance = {"resolver_checked": True}
            if note:
                provenance["note"] = note
            rows.append(
                {
                    "label": f"{category}-{i:03d}",
                    "category": category,
                    "smiles": pubchem_canonical,
                    "common_name": name,
                    "source": "PubChem+OPSIN name resolution, agreed",
                    "provenance": provenance,
                }
            )
        print(f"    [{i + 1}/{len(names)}] {name!r}: {outcome}", file=sys.stderr)
    return rows, dropped


def cmd_resolve(_args: argparse.Namespace) -> None:
    protocol = load_protocol()
    SCRATCH.mkdir(parents=True, exist_ok=True)

    plan = {
        "amino_acids_and_peptides": _AMINO_ACID_NAMES,
        "solvents": _solvent_names(),
        "reagents_and_protecting_groups": protocol["category"]["reagents_and_protecting_groups"]["reagents"],
        "sugars": protocol["category"]["sugars"]["sugars"],
        "vitamins": protocol["category"]["vitamins"]["vitamins"],
        "dyes": protocol["category"]["dyes"]["dyes"],
    }
    for category, names in plan.items():
        rows, dropped = resolve_names(category, names)
        (SCRATCH / f"{category}.json").write_text(json.dumps(rows, indent=1), encoding="utf-8")
        (SCRATCH / f"{category}_dropped.json").write_text(json.dumps(dropped, indent=1), encoding="utf-8")
        print(f"{category}: {len(rows)} resolved, {len(dropped)} dropped -> {SCRATCH / f'{category}.json'}")


# =====================================================================================================
# ChEMBL: the approved_drugs_chembl category. Structure identity comes from ChEMBL directly; PubChem
# cross-checks by name only where ChEMBL gives one (plan B2.2, protocol [category.approved_drugs_chembl]).
# =====================================================================================================

_CHEMBL_BASE = "https://www.ebi.ac.uk/chembl/api/data"
_CHEMBL_SEED = 20260922


def _chembl_get(path: str) -> dict:
    from openchem.net import open_url

    with open_url(f"{_CHEMBL_BASE}/{path}", timeout=30) as response:
        return json.loads(response.read())


def chembl_release_version() -> str:
    return str(_chembl_get("status.json").get("chembl_db_version", "unknown"))


def fetch_max_phase4_ids() -> list[str]:
    """Every ChEMBL molecule id at max_phase=4, paginated. IDs only -- keeps the payload small."""
    import time

    ids: list[str] = []
    offset = 0
    limit = 1000
    while True:
        payload = _chembl_get(
            f"molecule.json?max_phase=4&limit={limit}&offset={offset}&only=molecule_chembl_id"
        )
        batch = [m["molecule_chembl_id"] for m in payload.get("molecules", [])]
        ids.extend(batch)
        total = (payload.get("page_meta") or {}).get("total_count")
        offset += limit
        print(f"  ...{len(ids)}{f'/{total}' if total is not None else ''} ids fetched", file=sys.stderr)
        if not batch or (total is not None and offset >= total):
            break
        time.sleep(0.3)
    return sorted(set(ids))


def sample_ids(pool: list[str], n: int, seed: int) -> list[str]:
    """A deterministic seeded sample, sorted first so the draw never depends on API response order."""
    import random

    rng = random.Random(seed)
    return sorted(rng.sample(sorted(pool), min(n, len(pool))))


def fetch_molecule_details(chembl_ids: list[str]) -> dict[str, dict]:
    """Batched via `molecule_chembl_id__in`, chunked to keep each URL and response small."""
    import time

    details: dict[str, dict] = {}
    for start in range(0, len(chembl_ids), 25):
        chunk = chembl_ids[start : start + 25]
        payload = _chembl_get(f"molecule.json?molecule_chembl_id__in={','.join(chunk)}&limit=1000")
        for m in payload.get("molecules", []):
            details[m["molecule_chembl_id"]] = m
        time.sleep(0.3)
    return details


def cmd_chembl(_args: argparse.Namespace) -> None:
    import time

    from openchem.chem import naming_providers as np

    protocol = load_protocol()
    cfg = protocol["category"]["approved_drugs_chembl"]
    SCRATCH.mkdir(parents=True, exist_ok=True)

    print("ChEMBL: fetching every max_phase=4 molecule id...", file=sys.stderr)
    release = chembl_release_version()
    pool = fetch_max_phase4_ids()
    print(f"  ChEMBL release {release}: {len(pool)} molecules at max_phase=4", file=sys.stderr)

    chosen = sample_ids(pool, cfg["count"], _CHEMBL_SEED)
    print(f"  sampled {len(chosen)} (seed {_CHEMBL_SEED}) -> fetching structures", file=sys.stderr)
    details = fetch_molecule_details(chosen)

    rows, dropped = [], []
    for i, cid in enumerate(chosen):
        record = details.get(cid)
        if record is None:
            dropped.append({"chembl_id": cid, "outcome": "RESOLVER_AMBIGUOUS", "reason": "ChEMBL returned no record for this id"})
            continue
        smiles = (record.get("molecule_structures") or {}).get("canonical_smiles")
        pref_name = record.get("pref_name")
        if not smiles:
            dropped.append({"chembl_id": cid, "outcome": "RESOLVER_AMBIGUOUS", "reason": "ChEMBL record has no canonical_smiles"})
            continue
        canonical = _canonical(smiles)
        if canonical is None:
            dropped.append({"chembl_id": cid, "outcome": "RESOLVER_AMBIGUOUS", "reason": "ChEMBL's SMILES did not parse in RDKit"})
            continue
        if not pref_name:
            # No name to cross-check against PubChem -- kept, but marked unchecked rather than silently
            # treated the same as a resolver-agreed row.
            rows.append(
                {
                    "label": f"approved_drugs_chembl-{cid}",
                    "category": "approved_drugs_chembl",
                    "smiles": canonical,
                    "common_name": None,
                    "source": f"ChEMBL {cid} (max_phase=4); no pref_name, so no PubChem cross-check was possible",
                    "provenance": {"chembl_id": cid, "resolver_checked": False},
                }
            )
            print(f"    [{i + 1}/{len(chosen)}] {cid}: kept, unchecked (no pref_name)", file=sys.stderr)
            continue
        time.sleep(_PUBCHEM_PACING_SECONDS)
        try:
            pubchem = _pubchem_lookup_with_retry(pref_name)
            pubchem_canonical = _canonical(pubchem.smiles)
        except np.NamingError as exc:
            dropped.append({"chembl_id": cid, "pref_name": pref_name, "outcome": "RESOLVER_AMBIGUOUS", "reason": f"PubChem: {exc}"})
            print(f"    [{i + 1}/{len(chosen)}] {cid} ({pref_name!r}): RESOLVER_AMBIGUOUS", file=sys.stderr)
            continue
        if pubchem_canonical != canonical:
            dropped.append(
                {
                    "chembl_id": cid, "pref_name": pref_name, "outcome": "RESOLVER_DISAGREE",
                    "chembl_smiles": canonical, "pubchem_smiles": pubchem_canonical,
                }
            )
            print(f"    [{i + 1}/{len(chosen)}] {cid} ({pref_name!r}): RESOLVER_DISAGREE", file=sys.stderr)
            continue
        rows.append(
            {
                "label": f"approved_drugs_chembl-{cid}",
                "category": "approved_drugs_chembl",
                "smiles": canonical,
                "common_name": pref_name,
                "source": f"ChEMBL {cid} (max_phase=4), cross-checked against PubChem by name",
                "provenance": {"chembl_id": cid, "resolver_checked": True},
            }
        )
        print(f"    [{i + 1}/{len(chosen)}] {cid} ({pref_name!r}): MATCH", file=sys.stderr)

    (SCRATCH / "approved_drugs_chembl.json").write_text(json.dumps(rows, indent=1), encoding="utf-8")
    (SCRATCH / "approved_drugs_chembl_dropped.json").write_text(json.dumps(dropped, indent=1), encoding="utf-8")
    meta = {
        "chembl_release": release,
        "max_phase4_pool_size": len(pool),
        "sample_seed": _CHEMBL_SEED,
        "sampled_ids": chosen,
    }
    (SCRATCH / "approved_drugs_chembl_meta.json").write_text(json.dumps(meta, indent=1), encoding="utf-8")
    print(f"approved_drugs_chembl: {len(rows)} resolved, {len(dropped)} dropped -> {SCRATCH / 'approved_drugs_chembl.json'}")


# =====================================================================================================
# Assemble: merge every scratch category into the committed benchmarks/naming/battery_r9.toml.
#
# tomllib (stdlib) reads TOML but cannot write it, and neither tomli_w nor tomlkit is installed here, so
# this is a small, DELIBERATELY MINIMAL serializer -- it only has to handle the value shapes this file's
# own rows actually use (str, bool, int, list[str], one level of nested table), not arbitrary TOML.
# =====================================================================================================


def _toml_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def _toml_scalar(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return f'"{_toml_escape(value)}"'
    if value is None:
        raise ValueError("TOML has no null; omit the key instead")
    raise TypeError(f"no TOML scalar rule for {type(value)}: {value!r}")


def _toml_table_body(d: dict, indent: str = "") -> list[str]:
    lines = []
    for key, value in d.items():
        if value is None:
            continue
        if isinstance(value, list):
            lines.append(f"{indent}{key} = [{', '.join(_toml_scalar(v) for v in value)}]")
        elif isinstance(value, dict):
            continue  # nested tables are handled by the caller as their own [table.sub] header
        else:
            lines.append(f"{indent}{key} = {_toml_scalar(value)}")
    return lines


def write_battery_toml(meta: dict, rows: list[dict]) -> str:
    out = [
        "# GENERATED by tools/naming_battery_build.py assemble -- do not hand-edit.",
        "# The ordinary-compound battery (naming round 9, B2). No row here is a preferred-name target:",
        '# every row\'s target_source is "none", per battery_r9_protocol.toml\'s own stated purpose.',
        "",
        "[meta]",
        *_toml_table_body(meta),
        "",
    ]
    for row in rows:
        out.append("[[row]]")
        provenance = row.pop("provenance", None)
        out.extend(_toml_table_body(row))
        out.append('target_source = "none"')
        if provenance:
            out.append("")
            out.append("[row.provenance]")
            out.extend(_toml_table_body(provenance))
        out.append("")
    return "\n".join(out) + "\n"


def _load_scratch(name: str) -> list[dict]:
    path = SCRATCH / f"{name}.json"
    if not path.exists():
        return []
    return json.loads(path.read_text(encoding="utf-8"))


def cmd_assemble(_args: argparse.Namespace) -> None:
    categories = [
        "functional_group_pairs", "salts", "dipeptides", "amino_acids_and_peptides",
        "solvents", "reagents_and_protecting_groups", "sugars", "vitamins", "dyes",
        "approved_drugs_chembl",
    ]
    rows: list[dict] = []
    counts: dict[str, int] = {}
    missing: list[str] = []
    for category in categories:
        category_rows = _load_scratch(category)
        if not category_rows and not (SCRATCH / f"{category}.json").exists():
            missing.append(category)
        counts[category] = len(category_rows)
        rows.extend(category_rows)

    meta = {
        "protocol_sha256": protocol_sha256(),
        "schema_version": 1,
        "total_rows": len(rows),
        "categories_present": [c for c in categories if counts.get(c, 0) or (SCRATCH / f'{c}.json').exists()],
        "categories_not_yet_built": missing,
    }
    out_path = BENCH / "battery_r9.toml"
    out_path.write_text(write_battery_toml(meta, rows), encoding="utf-8")

    print(f"assembled {len(rows)} rows -> {out_path}")
    for category in categories:
        flag = " (NOT YET BUILT)" if category in missing else ""
        print(f"  {category:32s} {counts.get(category, 0):4d}{flag}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("generate", help="rule-based categories only, no network")
    sub.add_parser("dipeptides", help="seeded dipeptides, built by rule, no network")
    sub.add_parser("resolve", help="name-based categories through PubChem + OPSIN, needs network")
    sub.add_parser("chembl", help="the ChEMBL max_phase=4 sample, needs network")
    sub.add_parser("assemble", help="merge every scratch category into the committed battery_r9.toml")
    args = parser.parse_args()
    {
        "generate": cmd_generate,
        "dipeptides": cmd_dipeptides,
        "resolve": cmd_resolve,
        "chembl": cmd_chembl,
        "assemble": cmd_assemble,
    }[args.command](args)


if __name__ == "__main__":
    main()
