"""Builds the ordinary-compound battery (naming round 9, B2) from `battery_r9_protocol.toml`.

B2 is discovery and regression, never a preference oracle (see the protocol file's own header): no row
built here ever becomes a preferred-name target. Every row instead carries how its structure was obtained,
so a later reader can tell "built by rule" (ground truth by construction) from "resolved by name" (only as
trustworthy as two independent lookups agreeing).

## Use

    python tools/naming_battery_build.py generate     # rule-based categories only, no network
    python tools/naming_battery_build.py resolve      # name-based categories: PubChem + OPSIN, needs network
    python tools/naming_battery_build.py chembl       # the ChEMBL max_phase=4 sample, needs network
    python tools/naming_battery_build.py assemble     # merge everything into benchmarks/naming/battery_r9.toml

Each subcommand writes its own scratch JSON under `benchmarks/naming/battery_scratch/` (gitignored data, not
committed) so a slow network step never has to be redone because a later step failed; `assemble` is the only
one that writes the committed file.
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BENCH = ROOT / "benchmarks" / "naming"
PROTOCOL = BENCH / "battery_r9_protocol.toml"
SCRATCH = BENCH / "battery_scratch"

sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(Path(__file__).resolve().parent))


def protocol_sha256() -> str:
    return hashlib.sha256(PROTOCOL.read_bytes()).hexdigest()


def load_protocol() -> dict:
    import tomllib

    return tomllib.loads(PROTOCOL.read_text(encoding="utf-8"))


# =====================================================================================================
# Rule-based generation: functional-group pairs. No lookup -- the SMILES IS the ground truth.
# =====================================================================================================

#: Every group's attachment fragment, split into what precedes ("before") and what follows ("after") the
#: propane-1,3-diyl backbone "CCC", so `before(A) + "CCC" + after(B)` is always a single valid SMILES for
#: the pair (A at C1, B at C3). Chosen so every fragment is a MINIMAL, unambiguous representative of its
#: group -- e.g. "ester" and "ether" use a methyl cap because a bare alkoxy/acyloxy needs a second carbon
#: to be a real ester/ether rather than a hydroxyl/alkoxide.
_GROUP_FRAGMENTS: dict[str, tuple[str, str]] = {
    "hydroxyl": ("O", "O"),
    "primary_amine": ("N", "N"),
    "carboxylic_acid": ("OC(=O)", "C(=O)O"),
    "ester": ("COC(=O)", "C(=O)OC"),
    "primary_amide": ("NC(=O)", "C(=O)N"),
    "nitrile": ("N#C", "C#N"),
    "chloro": ("Cl", "Cl"),
    "ether": ("CO", "OC"),
    "ketone": ("CC(=O)", "C(=O)C"),
    "aldehyde": ("O=C", "C=O"),
    "nitro": ("[O-][N+](=O)", "[N+](=O)[O-]"),
    "thiol": ("S", "S"),
}

_FALLBACK_BACKBONE = "CCCCCC"  # hexane-1,6-diyl, logged when used


def generate_functional_group_pairs(groups: list[str]) -> list[dict]:
    from rdkit import Chem

    missing = [g for g in groups if g not in _GROUP_FRAGMENTS]
    if missing:
        raise SystemExit(f"no fragment defined for group(s): {missing}")

    rows = []
    for a, b in itertools.combinations(groups, 2):
        before_a, _ = _GROUP_FRAGMENTS[a]
        _, after_b = _GROUP_FRAGMENTS[b]
        scaffold = "CCC"
        smiles = f"{before_a}{scaffold}{after_b}"
        mol = Chem.MolFromSmiles(smiles)
        used_fallback = False
        if mol is None:
            # The escape hatch the protocol promises: try the longer backbone before giving up.
            used_fallback = True
            scaffold = _FALLBACK_BACKBONE
            smiles = f"{before_a}{scaffold}{after_b}"
            mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            raise SystemExit(f"functional_group_pairs: could not build a structure for ({a}, {b}): {smiles!r}")
        canonical = Chem.MolToSmiles(mol)
        rows.append(
            {
                "label": f"fgp-{a}+{b}",
                "category": "functional_group_pairs",
                "smiles": canonical,
                "source": "generated by rule",
                "provenance": {"groups": [a, b], "scaffold": "propane-1,3-diyl" if not used_fallback else "hexane-1,6-diyl (fallback)"},
            }
        )
    return rows


# =====================================================================================================
# Rule-based generation: salts. No lookup -- charge-balanced multi-component SMILES built directly.
# =====================================================================================================

_ION_SMILES: dict[str, tuple[str, int]] = {
    # name -> (SMILES, charge)
    "Na+": ("[Na+]", 1),
    "K+": ("[K+]", 1),
    "NH4+": ("[NH4+]", 1),
    "Ca2+": ("[Ca+2]", 2),
    "Mg2+": ("[Mg+2]", 2),
    "Fe3+": ("[Fe+3]", 3),
    "Cl-": ("[Cl-]", -1),
    "Br-": ("[Br-]", -1),
    "NO3-": ("[N+](=O)([O-])[O-]", -1),
    "SO4_2-": ("[O-]S(=O)(=O)[O-]", -2),
    "CO3_2-": ("[O-]C(=O)[O-]", -2),
    "PO4_3-": ("[O-]P(=O)([O-])[O-]", -3),
}

#: Only these reduced cation:anion ratios are built -- a genuine restriction, not an oversight: the
#: protocol commits to it before any salt is generated, so a combination needing e.g. 1:3 (FeCl3) is
#: dropped and counted rather than silently included with a different ratio rule applied after the fact.
_ALLOWED_RATIOS = {(1, 1), (1, 2), (2, 1)}


def _reduced_ratio(cation_charge: int, anion_charge: int) -> tuple[int, int]:
    import math

    a, c = abs(anion_charge), abs(cation_charge)
    g = math.gcd(a, c)
    return (a // g, c // g)  # (n_cations, n_anions)


def generate_salts(cations: list[str], anions: list[str]) -> tuple[list[dict], list[dict]]:
    from rdkit import Chem

    rows, dropped = [], []
    for cation_name, anion_name in itertools.product(cations, anions):
        cation_smiles, cation_charge = _ION_SMILES[cation_name]
        anion_smiles, anion_charge = _ION_SMILES[anion_name]
        n_cation, n_anion = _reduced_ratio(cation_charge, anion_charge)
        if (n_cation, n_anion) not in _ALLOWED_RATIOS:
            dropped.append(
                {
                    "cation": cation_name, "anion": anion_name,
                    "reason": f"needs a {n_cation}:{n_anion} ratio, outside {{1:1, 1:2, 2:1}}",
                }
            )
            continue
        smiles = ".".join([cation_smiles] * n_cation + [anion_smiles] * n_anion)
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            raise SystemExit(f"salts: could not build {cation_name}/{anion_name}: {smiles!r}")
        canonical = Chem.MolToSmiles(mol)
        rows.append(
            {
                "label": f"salt-{cation_name}+{anion_name}",
                "category": "salts",
                "smiles": canonical,
                "source": "generated by rule",
                "provenance": {"cation": cation_name, "anion": anion_name, "ratio": f"{n_cation}:{n_anion}"},
            }
        )
    return rows, dropped


def cmd_generate(_args: argparse.Namespace) -> None:
    protocol = load_protocol()
    SCRATCH.mkdir(parents=True, exist_ok=True)

    fgp = generate_functional_group_pairs(protocol["category"]["functional_group_pairs"]["groups"])
    (SCRATCH / "functional_group_pairs.json").write_text(json.dumps(fgp, indent=1), encoding="utf-8")
    print(f"functional_group_pairs: {len(fgp)} rows -> {SCRATCH / 'functional_group_pairs.json'}")

    salt_cfg = protocol["category"]["salts"]
    salts, dropped = generate_salts(salt_cfg["cations"], salt_cfg["anions"])
    (SCRATCH / "salts.json").write_text(json.dumps(salts, indent=1), encoding="utf-8")
    (SCRATCH / "salts_dropped.json").write_text(json.dumps(dropped, indent=1), encoding="utf-8")
    print(f"salts: {len(salts)} rows ({len(dropped)} combinations dropped for ratio) -> {SCRATCH / 'salts.json'}")
    expected = salt_cfg["count"]
    if len(salts) != expected:
        print(
            f"  NOTE: protocol says count={expected}, generator produced {len(salts)}. "
            f"Update battery_r9_protocol.toml's [category.salts].count to match -- this is the actual, "
            f"computed charge-balance result, not a target to force the generator toward.",
            file=sys.stderr,
        )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("generate", help="rule-based categories only, no network")
    args = parser.parse_args()
    {"generate": cmd_generate}[args.command](args)


if __name__ == "__main__":
    main()
